#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BASELINE="$SCRIPT_DIR/governance-checksums.json"
TODAY="$(date '+%Y-%m-%d')"

cd "$REPO_ROOT"

python - "$BASELINE" "$TODAY" <<'PY'
import json
import hashlib
import sys
from pathlib import Path

baseline_path = Path(sys.argv[1])
today = sys.argv[2]

MONITORED = [
    "AGENTS.md",
    "CLAUDE.md",
    "SSOT.md",
    "docs/style/VOICE.md",
]

checksums = {}
for rel_path in MONITORED:
    target = Path(rel_path)
    if not target.exists():
        print(f"WARNING: {rel_path} not found — skipping", file=sys.stderr)
        continue
    checksums[rel_path] = hashlib.sha256(target.read_bytes()).hexdigest()

baseline = {
    "_note": "SHA-256 checksums of canonical governance files. Generated by update-checksums.sh. Update after any intentional change to these files by running: bash .claude/hooks/update-checksums.sh",
    "_generated": today,
    "files": checksums,
}

baseline_path.write_text(
    json.dumps(baseline, indent=2) + "\n",
    encoding="utf-8",
)

print(f"Updated {baseline_path}")
for rel_path, sha in checksums.items():
    print(f"  {sha}  {rel_path}")
PY
