groups:
  - name: application_alerts
    interval: 30s
    rules:
      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has error rate above 5% (current value: {{ $value }})"

      # API Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 10m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High response time on {{ $labels.instance }}"
          description: "95th percentile response time is above 1 second (current value: {{ $value }}s)"

      # Service Down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 90% (current value: {{ $value }})"

      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% (current value: {{ $value }})"

      # Disk Space
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
        for: 5m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space on {{ $labels.instance }} is below 10% (current available: {{ $value }})"

  - name: database_alerts
    interval: 30s
    rules:
      # Database Connection Pool
      - alert: DatabaseConnectionPoolExhausted
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Database {{ $labels.datname }} using {{ $value }}% of max connections"

      # Database Replication Lag
      - alert: DatabaseReplicationLag
        expr: pg_replication_lag > 10
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Database replication lag detected"
          description: "Replication lag is {{ $value }} seconds"

      # Long Running Queries
      - alert: LongRunningQueries
        expr: pg_stat_activity_max_tx_duration > 300
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Long running database queries detected"
          description: "Query running for more than {{ $value }} seconds"

  - name: redis_alerts
    interval: 30s
    rules:
      # Redis Memory Usage
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Redis memory usage high"
          description: "Redis using {{ $value }}% of max memory"

      # Redis Connection Count
      - alert: RedisHighConnections
        expr: redis_connected_clients > 1000
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High number of Redis connections"
          description: "{{ $value }} clients connected to Redis"

  - name: business_alerts
    interval: 1m
    rules:
      # Low Traffic Alert
      - alert: LowTraffic
        expr: rate(http_requests_total[5m]) < 10
        for: 10m
        labels:
          severity: info
          team: business
        annotations:
          summary: "Low traffic on {{ $labels.app }}"
          description: "{{ $labels.app }} receiving less than 10 requests per minute"

      # High Bounce Rate
      - alert: HighBounceRate
        expr: rate(page_bounce_total[5m]) / rate(page_view_total[5m]) > 0.7
        for: 15m
        labels:
          severity: warning
          team: product
        annotations:
          summary: "High bounce rate on {{ $labels.app }}"
          description: "Bounce rate is {{ $value }}% on {{ $labels.app }}"

      # Registration Drop
      - alert: RegistrationDrop
        expr: rate(user_registration_total[1h]) < 0.5 * rate(user_registration_total[1h] offset 1d)
        for: 1h
        labels:
          severity: warning
          team: business
        annotations:
          summary: "Registration rate dropped significantly"
          description: "Registration rate is {{ $value }}% compared to yesterday"

  - name: security_alerts
    interval: 30s
    rules:
      # Failed Login Attempts
      - alert: HighFailedLoginAttempts
        expr: rate(authentication_failures_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High number of failed login attempts"
          description: "{{ $value }} failed login attempts per minute"

      # SSL Certificate Expiry
      - alert: SSLCertificateExpirySoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1h
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "SSL certificate expiring soon for {{ $labels.instance }}"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value }} seconds"

      # Suspicious Activity
      - alert: SuspiciousActivity
        expr: rate(suspicious_activity_total[5m]) > 5
        for: 5m
        labels:
          severity: critical
          team: security
        annotations:
          summary: "Suspicious activity detected"
          description: "{{ $value }} suspicious activities detected per minute"