#!/usr/bin/env node

/**
 * REPZ Platform Setup Helper
 * Interactive script to help set up your environment
 */

import { createInterface } from 'readline';
import { writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

function printHeader() {
  console.log('\n' + '='.repeat(60));
  console.log('🚀 REPZ Platform Setup Helper');
  console.log('='.repeat(60) + '\n');
}

function printSuccess(message) {
  console.log('✅', message);
}

function printError(message) {
  console.log('❌', message);
}

function printInfo(message) {
  console.log('ℹ️ ', message);
}

function printStep(step, message) {
  console.log(`\n📍 Step ${step}: ${message}`);
  console.log('-'.repeat(60));
}

async function main() {
  printHeader();
  
  console.log('This script will help you set up your REPZ platform.\n');
  console.log('You will need:');
  console.log('  1. A Supabase account (free)');
  console.log('  2. Your Supabase project URL');
  console.log('  3. Your Supabase anon key\n');
  
  const ready = await question('Are you ready to start? (yes/no): ');
  
  if (ready.toLowerCase() !== 'yes' && ready.toLowerCase() !== 'y') {
    console.log('\nNo problem! When you\'re ready, run this script again.');
    console.log('In the meantime, check out QUICK-START.md for manual instructions.\n');
    rl.close();
    return;
  }

  // Check if .env.local already exists
  const envPath = join(__dirname, '.env.local');
  if (existsSync(envPath)) {
    console.log('\n⚠️  Warning: .env.local already exists!');
    const overwrite = await question('Do you want to overwrite it? (yes/no): ');
    if (overwrite.toLowerCase() !== 'yes' && overwrite.toLowerCase() !== 'y') {
      console.log('\nSetup cancelled. Your existing .env.local was not modified.\n');
      rl.close();
      return;
    }
  }

  // Step 1: Supabase Account
  printStep(1, 'Supabase Account');
  console.log('First, you need a Supabase account.\n');
  console.log('👉 Go to: https://supabase.com/dashboard');
  console.log('   - Sign up or log in');
  console.log('   - Create a new project');
  console.log('   - Wait for it to be ready (2-3 minutes)\n');
  
  const hasAccount = await question('Have you created your Supabase project? (yes/no): ');
  
  if (hasAccount.toLowerCase() !== 'yes' && hasAccount.toLowerCase() !== 'y') {
    console.log('\nPlease create your Supabase project first, then run this script again.');
    console.log('See QUICK-START.md for detailed instructions.\n');
    rl.close();
    return;
  }

  // Step 2: Get API Keys
  printStep(2, 'Get Your API Keys');
  console.log('In your Supabase project:');
  console.log('  1. Click Settings (gear icon) → API');
  console.log('  2. Copy your Project URL');
  console.log('  3. Copy your anon/public key\n');

  let supabaseUrl = await question('Paste your Supabase Project URL: ');
  supabaseUrl = supabaseUrl.trim();

  // Validate URL
  if (!supabaseUrl.startsWith('https://') || !supabaseUrl.includes('.supabase.co')) {
    printError('Invalid Supabase URL format!');
    console.log('Expected format: https://xxxxx.supabase.co');
    console.log('Please run the script again with the correct URL.\n');
    rl.close();
    return;
  }

  let supabaseKey = await question('Paste your Supabase anon key: ');
  supabaseKey = supabaseKey.trim();

  // Validate key
  if (!supabaseKey.startsWith('eyJ')) {
    printError('Invalid Supabase key format!');
    console.log('The anon key should start with "eyJ"');
    console.log('Please run the script again with the correct key.\n');
    rl.close();
    return;
  }

  // Step 3: Optional Stripe
  printStep(3, 'Stripe Configuration (Optional)');
  console.log('Stripe is needed for payment processing.');
  console.log('You can skip this for now and add it later.\n');
  
  const addStripe = await question('Do you want to add Stripe now? (yes/no): ');
  
  let stripeKey = '';
  if (addStripe.toLowerCase() === 'yes' || addStripe.toLowerCase() === 'y') {
    console.log('\nIn your Stripe dashboard (https://dashboard.stripe.com):');
    console.log('  1. Switch to Test Mode (toggle in top right)');
    console.log('  2. Go to Developers → API keys');
    console.log('  3. Copy your Publishable key (starts with pk_test_)\n');
    
    stripeKey = await question('Paste your Stripe publishable key (or press Enter to skip): ');
    stripeKey = stripeKey.trim();
  }

  // Step 4: Create .env.local
  printStep(4, 'Creating .env.local file');
  
  const envContent = `# Supabase Configuration
# Generated by setup-helper.js on ${new Date().toISOString()}
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseKey}

# Stripe Configuration (Optional)
${stripeKey ? `VITE_STRIPE_PUBLISHABLE_KEY=${stripeKey}` : '# VITE_STRIPE_PUBLISHABLE_KEY=pk_test_your-key-here'}

# App Configuration
VITE_APP_URL=http://localhost:8080
VITE_API_URL=http://localhost:8080/api
`;

  try {
    writeFileSync(envPath, envContent);
    printSuccess('.env.local file created successfully!');
  } catch (error) {
    printError('Failed to create .env.local file');
    console.log('Error:', error.message);
    console.log('\nYou can create it manually. See .env.example for the format.\n');
    rl.close();
    return;
  }

  // Step 5: Database Schema
  printStep(5, 'Deploy Database Schema');
  console.log('Now you need to deploy the database schema to Supabase.\n');
  console.log('In your Supabase project:');
  console.log('  1. Click SQL Editor in the left sidebar');
  console.log('  2. Click "New query"');
  console.log('  3. Open: organizations/repz-llc/supabase/schema.sql');
  console.log('  4. Copy ALL content (Ctrl+A, Ctrl+C)');
  console.log('  5. Paste into SQL Editor (Ctrl+V)');
  console.log('  6. Click "Run" button');
  console.log('  7. Wait for "Success. No rows returned"\n');
  
  const schemaDeployed = await question('Have you deployed the schema? (yes/no): ');
  
  if (schemaDeployed.toLowerCase() !== 'yes' && schemaDeployed.toLowerCase() !== 'y') {
    console.log('\n⚠️  Important: You must deploy the schema before using the app!');
    console.log('See QUICK-START.md Step 3 for detailed instructions.\n');
  }

  // Step 6: Storage Buckets
  printStep(6, 'Create Storage Buckets (Optional)');
  console.log('Storage buckets are needed for file uploads (avatars, videos, photos).');
  console.log('You can skip this for now and add them later.\n');
  
  const createBuckets = await question('Do you want instructions for creating buckets? (yes/no): ');
  
  if (createBuckets.toLowerCase() === 'yes' || createBuckets.toLowerCase() === 'y') {
    console.log('\nIn your Supabase project:');
    console.log('  1. Click Storage in the left sidebar');
    console.log('  2. Click "Create a new bucket"');
    console.log('  3. Create these buckets:');
    console.log('     - avatars (public, 2MB limit)');
    console.log('     - workout-videos (public, 100MB limit)');
    console.log('     - progress-photos (private, 5MB limit)\n');
    console.log('See SETUP-CHECKLIST.md Step 5 for detailed instructions.\n');
  }

  // Final Steps
  printStep(7, 'Start the Application');
  console.log('\nYou\'re all set! Now you can start the development server:\n');
  console.log('  cd organizations/repz-llc/apps/repz');
  console.log('  npm install  # (if you haven\'t already)');
  console.log('  npm run dev\n');
  console.log('Then open: http://localhost:8080\n');

  printSuccess('Setup complete! 🎉\n');
  
  console.log('Next steps:');
  console.log('  1. Start the dev server (npm run dev)');
  console.log('  2. Open http://localhost:8080');
  console.log('  3. Sign up for an account');
  console.log('  4. Explore the features!\n');
  
  console.log('Need help? Check out:');
  console.log('  - QUICK-START.md (quick guide)');
  console.log('  - SETUP-CHECKLIST.md (detailed checklist)');
  console.log('  - SUPABASE-SETUP-GUIDE.md (comprehensive guide)\n');

  rl.close();
}

main().catch(error => {
  console.error('\n❌ An error occurred:', error.message);
  console.log('\nPlease check the error and try again.');
  console.log('If you need help, see QUICK-START.md for manual instructions.\n');
  rl.close();
  process.exit(1);
});
