// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayfvtntapmfpzxwaqwrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZnZ0bnRhcG1mcHp4d2Fxd3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDkyNDYsImV4cCI6MjA3MDIyNTI0Nn0.Or0UPScDFBjU-eBmY54Y2mnn287Eb_ilMaFlsEqE4jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});