"""Assemble alawein/docs/style/voice-unified.md from block source files.

Reads four block source files (VOICE.md, voice-software-register.md,
voice-surfaces.md, voice-workflow.md), strips frontmatter, drops the leading
block-naming H1, demotes remaining headers one level, synthesizes block headers
from the BLOCKS config, and writes voice-unified.md with frontmatter whose
last_updated reflects the newest source file commit date.

Run from the alawein repo root: python scripts/ops/build_voice_unified.py
"""
from __future__ import annotations

import re
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Iterable, Optional, TypedDict

REPO_ROOT = Path(__file__).resolve().parents[2]
STYLE_DIR = REPO_ROOT / "docs" / "style"
OUTPUT_PATH = STYLE_DIR / "voice-unified.md"


class BlockSpec(TypedDict):
    file: Path
    title: str
    subtitle: Optional[str]


BLOCKS: list[BlockSpec] = [
    {
        "file": STYLE_DIR / "VOICE.md",
        "title": "Block 1 · Universal Core",
        "subtitle": "_Source: `alawein/docs/style/VOICE.md`. Applies to every surface, no exceptions._",
    },
    {
        "file": STYLE_DIR / "voice-software-register.md",
        "title": "Block 2 · Design-Defense Register",
        "subtitle": "_Applies to `[software-doc]` and `[notebook]` surfaces. Not active for physics papers, READMEs, or prompt kits._",
    },
    {
        "file": STYLE_DIR / "voice-surfaces.md",
        "title": "Block 3 · Surface Adjustments",
        "subtitle": "_Switch in the section that matches the surface tag. Block 1 always applies._",
    },
    {
        "file": STYLE_DIR / "voice-workflow.md",
        "title": "Block 4 · Polish Workflow",
        "subtitle": None,
    },
]


def strip_frontmatter(text: str) -> str:
    """Strip leading YAML frontmatter (--- ... ---) if present."""
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---\n", 4)
    if end == -1:
        return text
    return text[end + len("\n---\n"):].lstrip("\n")


def drop_leading_h1(text: str) -> str:
    """Drop the first non-blank line if it is an H1 (`# `).

    Also drops any leading blank lines before the H1 and one immediately-
    following blank line for clean spacing.
    Leaves text unchanged if the first non-blank line is not an H1.
    """
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if not line.strip():
            continue
        stripped = line.lstrip()
        if stripped.startswith("# ") and not stripped.startswith("## "):
            # Drop leading blank lines, the H1 itself, and one trailing blank.
            del lines[: i + 1]
            if lines and not lines[0].strip():
                del lines[0]
            return "".join(lines)
        return text
    return text


def demote_headers(text: str) -> str:
    """Add one `#` to every line beginning with `#+ ` (markdown header)."""
    return re.sub(r"^(#+)(\s)", r"#\1\2", text, flags=re.MULTILINE)


def get_last_updated(repo_root: Path, files: Iterable[Path]) -> str:
    """Return the maximum git commit date (YYYY-MM-DD) across the given files.

    Falls back to today's date for any file with no git history (e.g., not yet
    committed). If no file has any history, returns today's date.
    """
    today = date.today().isoformat()
    dates: list[str] = []
    for f in files:
        try:
            rel = f.relative_to(repo_root)
        except ValueError:
            rel = f
        result = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", str(rel)],
            cwd=repo_root,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        out = result.stdout.strip()
        dates.append(out if (result.returncode == 0 and out) else today)
    return max(dates) if dates else today


def _process_block(spec: BlockSpec) -> str:
    """Read one block source, strip frontmatter, drop leading H1, demote headers."""
    raw = spec["file"].read_text(encoding="utf-8")
    body = drop_leading_h1(strip_frontmatter(raw))
    return demote_headers(body).rstrip() + "\n"


def assemble(blocks: list[BlockSpec], today: str, last_updated: str) -> str:
    """Assemble all blocks into the unified guide text."""
    sources_field = ", ".join(f"docs/style/{spec['file'].name}" for spec in blocks)
    parts = [
        "---\n",
        "type: generated\n",
        f"source: {sources_field}\n",
        "sync: scripts/ops/build_voice_unified.py\n",
        "sla: regenerate on source change\n",
        "authority: derived\n",
        "audience: [contributors, agents, llm-system-prompts]\n",
        f"last_updated: {last_updated}\n",
        "---\n\n",
        "<!-- Generated by scripts/ops/build_voice_unified.py from docs/style/. Do not hand-edit. -->\n",
        "<!-- markdownlint-disable MD049 -->\n\n",
        "# Meshal Alawein — Voice Guide\n\n",
        f"_Generated: {today}. Unified reference for all writing surfaces._\n",
        "_Works as an AI system prompt and as a personal review checklist._\n\n",
        "## How to use\n\n",
        "**As an AI system prompt:** paste this guide in full, then tag the target surface: "
        "`[software-doc]`, `[notebook]`, `[readme]`, `[physics-paper]`, `[claude-md]`, or `[prompt-kit]`. "
        "Apply Block 1 universally. Apply Block 2 to `[software-doc]` and `[notebook]` surfaces. "
        "For `[physics-paper]`, apply only §10 and §11 from Block 2; all other Block 2 sections are inactive. "
        "Apply the matching § from Block 3 for surface-specific adjustments. "
        "Run §24 as a final audit pass before returning output.\n\n",
        "**As a personal checklist:** use §23 before writing and §24 after.\n",
    ]

    for spec in blocks:
        parts.append("\n---\n\n")
        parts.append(f"## {spec['title']}\n")
        if spec["subtitle"]:
            parts.append(f"{spec['subtitle']}\n\n")
        parts.append(_process_block(spec))

    return "".join(parts)


def main() -> int:
    missing = [str(spec["file"]) for spec in BLOCKS if not spec["file"].exists()]
    if missing:
        print(f"ERROR: missing source files: {', '.join(missing)}", file=sys.stderr)
        return 1

    last_updated = get_last_updated(REPO_ROOT, [spec["file"] for spec in BLOCKS])
    today = date.today().isoformat()
    body = assemble(BLOCKS, today=today, last_updated=last_updated)

    OUTPUT_PATH.write_text(body, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH} ({len(body):,} chars, last_updated={last_updated})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
