"""Assemble alawein/docs/style/voice-unified.md from block source files.

Reads four block source files (VOICE.md, voice-software-register.md,
voice-surfaces.md, voice-workflow.md), strips frontmatter, drops the leading
block-naming H1, demotes remaining headers one level, synthesizes block headers
from the BLOCKS config, and writes voice-unified.md with frontmatter whose
last_updated reflects the newest source file commit date.

Run from the alawein repo root: python scripts/ops/build_voice_unified.py
"""
from __future__ import annotations

import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, TypedDict

REPO_ROOT = Path(__file__).resolve().parents[2]
STYLE_DIR = REPO_ROOT / "docs" / "style"
OUTPUT_PATH = STYLE_DIR / "voice-unified.md"


class BlockSpec(TypedDict):
    file: Path
    title: str
    subtitle: Optional[str]


BLOCKS: list[BlockSpec] = [
    {
        "file": STYLE_DIR / "VOICE.md",
        "title": "Block 1 · Universal Core",
        "subtitle": "_Source: `alawein/docs/style/VOICE.md`. Applies to every surface, no exceptions._",
    },
    # Blocks 2-4 source files carry their own subtitle paragraph after the
    # leading H1, so the assembler should not synthesize one (would duplicate).
    # Block 1 (VOICE.md) does not, so its subtitle is synthesized above.
    {
        "file": STYLE_DIR / "voice-software-register.md",
        "title": "Block 2 · Design-Defense Register",
        "subtitle": None,
    },
    {
        "file": STYLE_DIR / "voice-surfaces.md",
        "title": "Block 3 · Surface Adjustments",
        "subtitle": None,
    },
    {
        "file": STYLE_DIR / "voice-workflow.md",
        "title": "Block 4 · Polish Workflow",
        "subtitle": None,
    },
]


def strip_frontmatter(text: str) -> str:
    """Strip leading YAML frontmatter (--- ... ---) if present."""
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---\n", 4)
    if end == -1:
        return text
    return text[end + len("\n---\n"):].lstrip("\n")


def drop_leading_h1(text: str) -> str:
    """Drop the first non-blank line if it is an H1 (`# `).

    Also drops any leading blank lines before the H1 and one immediately-
    following blank line for clean spacing.
    Leaves text unchanged if the first non-blank line is not an H1.
    """
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if not line.strip():
            continue
        stripped = line.lstrip()
        if stripped.startswith("# ") and not stripped.startswith("## "):
            # Drop leading blank lines, the H1 itself, and one trailing blank.
            del lines[: i + 1]
            if lines and not lines[0].strip():
                del lines[0]
            return "".join(lines)
        return text
    return text


def demote_headers(text: str) -> str:
    """Add one `#` to every line beginning with `#+ ` (markdown header).

    Skips lines inside fenced code blocks (between ``` markers) so that
    code comments using `#` (Python, shell, etc.) are not corrupted.
    """
    lines = text.splitlines(keepends=True)
    in_fence = False
    out = []
    for line in lines:
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
        else:
            out.append(re.sub(r"^(#+)(\s)", r"#\1\2", line))
    return "".join(out)


def _process_block(spec: BlockSpec) -> str:
    """Read one block source, strip frontmatter, drop leading H1, demote headers."""
    raw = spec["file"].read_text(encoding="utf-8")
    body = drop_leading_h1(strip_frontmatter(raw))
    return demote_headers(body).rstrip() + "\n"


def assemble(blocks: list[BlockSpec], today: str, last_updated: str) -> str:
    """Assemble all blocks into the unified guide text."""
    sources_field = ", ".join(f"docs/style/{spec['file'].name}" for spec in blocks)
    parts = [
        "---\n",
        "type: generated\n",
        f"source: {sources_field}\n",
        "sync: scripts/ops/build_voice_unified.py\n",
        "sla: regenerate on source change\n",
        "authority: derived\n",
        "audience: [contributors, agents, llm-system-prompts]\n",
        f"last_updated: {last_updated}\n",
        "---\n\n",
        "<!-- Generated by scripts/ops/build_voice_unified.py from docs/style/. Do not hand-edit. -->\n",
        "<!-- markdownlint-disable MD049 -->\n\n",
        "# Meshal Alawein — Voice Guide\n\n",
        f"_Generated: {today}. Unified reference for all writing surfaces._\n",
        "_Works as an AI system prompt and as a personal review checklist._\n\n",
        "## How to use\n\n",
        "**As an AI system prompt:** paste this guide in full, then tag the target surface: "
        "`[software-doc]`, `[notebook]`, `[readme]`, `[physics-paper]`, `[claude-md]`, or `[prompt-kit]`. "
        "Apply Block 1 universally. Apply Block 2 to `[software-doc]` and `[notebook]` surfaces. "
        "For `[physics-paper]`, apply only §10 and §11 from Block 2; all other Block 2 sections are inactive. "
        "Apply the matching § from Block 3 for surface-specific adjustments. "
        "Run §24 as a final audit pass before returning output.\n\n",
        "**As a personal checklist:** use §23 before writing and §24 after.\n",
    ]

    for spec in blocks:
        parts.append("\n---\n\n")
        parts.append(f"## {spec['title']}\n")
        if spec["subtitle"]:
            parts.append(f"{spec['subtitle']}\n\n")
        parts.append(_process_block(spec))

    return "".join(parts)


def main() -> int:
    missing = [str(spec["file"]) for spec in BLOCKS if not spec["file"].exists()]
    if missing:
        print(f"ERROR: missing source files: {', '.join(missing)}", file=sys.stderr)
        return 1

    # Use UTC date for last_updated so the doctrine validator's freshness check
    # (which compares against today's UTC date in CI) passes consistently.
    # Git log %cs of source files would be stable across same-day commits in
    # the committer's local timezone, which doesn't satisfy the validator's
    # "must bump on every commit" rule.
    last_updated = datetime.now(timezone.utc).date().isoformat()
    today = last_updated
    body = assemble(BLOCKS, today=today, last_updated=last_updated)

    OUTPUT_PATH.write_text(body, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH} ({len(body):,} chars, last_updated={last_updated})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
