#!/usr/bin/env bash
# pre-commit-doctrine.sh -- Docs Doctrine pre-commit gate
# Part of Docs Doctrine (Phase 5: Full Enforcement)
#
# Install: deploy via scripts/deploy-hooks.sh or manually:
#   cp scripts/pre-commit-doctrine.sh .git/hooks/pre-commit
#   chmod +x .git/hooks/pre-commit
set -euo pipefail

echo "-- Docs Doctrine: pre-commit validation --"

# Get staged files
STAGED=$(git diff --cached --name-only --diff-filter=ACM)

if [ -z "$STAGED" ]; then
  echo "No staged files. Skipping."
  exit 0
fi

FAIL=0

# -- Rule 5: Quick naming checks on staged files --
for file in $STAGED; do
  base=$(basename "$file")
  # Ban backup extensions
  if [[ "$base" =~ \.(bak|old|tmp|orig)$ ]]; then
    echo "FAIL [R5] Banned extension: $file"
    FAIL=1
  fi
  # Ban version suffixes
  if [[ "$base" =~ (_v[0-9]+|_final|_new|_old|_copy|_backup)\. ]]; then
    echo "FAIL [R5] Banned suffix: $file"
    FAIL=1
  fi
done

# -- Rules 1-4: Header validation (managed .md files only) --
# JSON files are skipped (cannot have YAML frontmatter)
# CI workflows, lockfiles, and config files in .github/ are excluded
for file in $STAGED; do
  # Skip files in non-doc directories
  case "$file" in
    .github/*|node_modules/*|.venv/*|.claude/settings*|claude-agent-platform/*) continue ;;
  esac

  ext="${file##*.}"
  case "$ext" in
    md)
      # GitHub-facing READMEs are intentionally frontmatter-free (see CLAUDE.md).
      if [ "$file" = "README.md" ] || [ "$file" = "docs/README.md" ]; then
        continue
      fi
      # Scaffolding templates are rendered into new repos on bootstrap; their
      # frontmatter, if any, belongs to the rendered repo, not the template.
      # Must stay aligned with EXEMPT_TEMPLATE_MARKDOWN_PATHS in
      # scripts/validate-doctrine.py.
      case "$file" in
        templates/scaffolding/README.product.md|\
        templates/scaffolding/README.research.md|\
        templates/scaffolding/README.tooling.md|\
        templates/scaffolding/docs-README.md)
          continue
          ;;
      esac
      if [ "$file" = "README.md" ] && head -1 "$file" | grep -q "^<!-- Generated by scripts/sync-readme.py"; then
        continue
      fi
      if [ -f "$file" ] && ! head -1 "$file" | grep -q "^---"; then
        echo "FAIL [R1] Missing doctrine header: $file"
        FAIL=1
      fi
      ;;
  esac
done

# NOTE: Full-repo validation (validate-doctrine.py) runs in CI, not here.
# The pre-commit hook only checks staged files for naming and header issues.
# This prevents bulk migrations from being blocked by pre-existing errors
# in unstaged files.

if [ $FAIL -ne 0 ]; then
  echo ""
  echo "Commit blocked by Docs Doctrine. Fix errors above."
  exit 1
fi

echo "Docs Doctrine: all checks passed."
