#!/usr/bin/env python3
"""Docs Doctrine Validator -- enforces all 10 rules.

Usage:
    python validate-doctrine.py [path]       # validate a directory
    python validate-doctrine.py --ci         # strict mode (exit 1 on any failure)
    python validate-doctrine.py --fix        # auto-add missing headers (interactive)
"""

import os
import sys
import re
import argparse
from datetime import date, timedelta
from pathlib import Path

try:
    import yaml  # type: ignore[import-not-found]
except ImportError:  # pragma: no cover -- yaml is in the CI pip install step
    yaml = None  # type: ignore[assignment]

# -- Configuration --
MANAGED_EXTENSIONS = {".md", ".json", ".yaml", ".yml", ".toml", ".cfg"}
# Frontmatter is enforced for Markdown only; config/metadata files are
# classified by path/governance rules, not in-file YAML blocks.
HEADER_EXTENSIONS = {".md"}
UPPERCASE_ROOT_PATTERN = re.compile(r"^[A-Z][A-Z0-9_-]*\.md$")
KEBAB_DIR_PATTERN = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
BANNED_SUFFIXES = ("_v2", "_v3", "_final", "_new", "_old", "_copy", "_backup")
BANNED_EXTENSIONS = (".bak", ".old", ".tmp", ".orig")
VALID_TYPES = {"canonical", "derived", "generated", "frozen"}
# Pre-doctrine type values retained in legacy files. Emit a warning (not an
# error) so the doctrine rollout can migrate these incrementally rather than
# blocking merges across every historical doc.
LEGACY_TYPES = {"normative", "guide", "lessons", "reference"}
VALID_SYNCS = {"ci", "script", "manual", "none"}
VALID_SLAS = {"realtime", "on-change", "manual", "none"}
PROFILE_README_MARKER = "<!-- Generated by scripts/sync-readme.py. Do not edit directly. -->"
EXEMPT_MARKDOWN_PATHS = {"README.md", "docs/README.md"}
EXEMPT_TEMPLATE_MARKDOWN_PATHS = {
    "templates/scaffolding/README.product.md",
    "templates/scaffolding/README.research.md",
    "templates/scaffolding/README.tooling.md",
    "templates/scaffolding/docs-README.md",
}


class ValidationResult:
    def __init__(self):
        self.errors = []
        self.warnings = []
        self.passed = 0

    def error(self, path, rule, msg):
        self.errors.append((path, rule, msg))

    def warn(self, path, rule, msg):
        self.warnings.append((path, rule, msg))

    def ok(self):
        self.passed += 1

    @property
    def success(self):
        return len(self.errors) == 0

    def report(self):
        print(f"\n{'=' * 60}")
        print("DOCTRINE VALIDATION REPORT")
        print(f"{'=' * 60}")
        print(f"Passed:   {self.passed}")
        print(f"Warnings: {len(self.warnings)}")
        print(f"Errors:   {len(self.errors)}")
        print(f"{'=' * 60}")
        for path, rule, msg in self.warnings:
            print(f"  WARN  [{rule}] {path}: {msg}")
        for path, rule, msg in self.errors:
            print(f"  FAIL  [{rule}] {path}: {msg}")
        print(f"\nResult: {'PASS' if self.success else 'FAIL'}")
        return self.success


def parse_header(filepath):
    """Extract and parse YAML frontmatter from a file.

    Returns (header_dict, body). Returns (None, content) when no frontmatter
    delimiter is present, the delimiter block is unclosed, the block contains
    invalid YAML, or the parsed block is not a mapping. Using real YAML
    parsing (when pyyaml is available) surfaces the CLAUDE.md-documented
    anti-pattern where bold/bullet syntax inside `---` renders as invalid YAML;
    the hand-rolled line scanner used to silently accept it.
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except (UnicodeDecodeError, PermissionError):
        return None, ""

    stripped = content.lstrip("\ufeff")
    if not stripped.startswith("---"):
        return None, content

    # Find the closing delimiter on its own line (not just any occurrence of
    # `---` in the body).
    lines = stripped.splitlines()
    closing_index = None
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            closing_index = idx
            break
    if closing_index is None:
        return None, content

    block = "\n".join(lines[1:closing_index])
    body = "\n".join(lines[closing_index + 1 :]).strip()

    if yaml is not None:
        try:
            parsed = yaml.safe_load(block)
        except yaml.YAMLError:
            return None, body
        if not isinstance(parsed, dict):
            return None, body
        header = {str(key): str(value) if value is not None else "" for key, value in parsed.items()}
        return header, body

    # Fallback line scanner (only if pyyaml is unavailable).
    header = {}
    for line in block.split("\n"):
        if ":" in line:
            key, val = line.split(":", 1)
            header[key.strip()] = val.strip()
    return header, body


def check_naming(filepath, result):
    """Rule 5: Naming conventions."""
    path = Path(filepath)
    name = path.name
    stem = path.stem

    # R5 only applies to managed file types — skip source code, notebooks, etc.
    if path.suffix not in MANAGED_EXTENSIONS:
        result.ok()
        return

    # Files in archive/ or dist/ get warnings, not errors (historical artifacts)
    parts = path.parts
    in_archive = any(p in ("archive", "dist") for p in parts)

    # Banned extensions
    if path.suffix in BANNED_EXTENSIONS:
        if in_archive:
            result.warn(filepath, "R5", f"Banned extension in archive: {path.suffix}")
        else:
            result.error(filepath, "R5", f"Banned extension: {path.suffix}")
        return

    # Banned suffixes
    for suffix in BANNED_SUFFIXES:
        if stem.endswith(suffix):
            if in_archive:
                result.warn(
                    filepath, "R5", f"Banned suffix in archive: {suffix}"
                )
            else:
                result.error(filepath, "R5", f"Banned version suffix: {suffix}")
            return

    # Root-level .md files must be UPPERCASE
    parent_name = path.parent.name
    if path.suffix == ".md" and parent_name in ("", "."):
        if not UPPERCASE_ROOT_PATTERN.match(name) and name != "docs-doctrine.md":
            result.warn(filepath, "R5", "Root .md should be UPPERCASE.md")

    result.ok()


def check_directory_naming(dirpath, result):
    """Rule 5: Directory names must be kebab-case."""
    name = Path(dirpath).name
    if name.startswith(".") or name.startswith("_") or name == "node_modules":
        return
    if not KEBAB_DIR_PATTERN.match(name):
        result.warn(dirpath, "R5", f"Directory should be kebab-case: {name}")
    result.ok()


def is_exempt_markdown(path: Path, root: Path, content: str) -> bool:
    rel = path.relative_to(root).as_posix()
    if rel in EXEMPT_MARKDOWN_PATHS:
        return True
    if rel in EXEMPT_TEMPLATE_MARKDOWN_PATHS:
        return True
    if rel == "README.md" and content.startswith(PROFILE_README_MARKER):
        return True
    return False


def check_header(filepath, result, root):
    """Rules 1, 3, 4: Classification header."""
    path = Path(filepath)
    suffix = path.suffix
    if suffix not in MANAGED_EXTENSIONS:
        return

    # Only markdown files are required to carry doctrine frontmatter.
    if suffix not in HEADER_EXTENSIONS:
        result.ok()
        return

    try:
        content = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, PermissionError):
        content = ""

    # GitHub-facing entrypoint READMEs are exempt from doctrine frontmatter so
    # repository surfaces do not render classification metadata to users.
    if is_exempt_markdown(path, root, content):
        if content.lstrip("\ufeff").startswith("---\n") or content.lstrip("\ufeff").startswith("---\r\n"):
            result.error(filepath, "R1", "GitHub-facing entrypoint READMEs must not include visible YAML frontmatter")
            return
        result.ok()
        return

    header, _ = parse_header(filepath)

    if header is None:
        result.error(filepath, "R1", "Missing doctrine header (YAML frontmatter)")
        return

    file_type = header.get("type", "").lower()
    if file_type in LEGACY_TYPES:
        result.warn(
            filepath,
            "R1",
            f"Pre-doctrine type '{file_type}' -- migrate to one of {sorted(VALID_TYPES)}",
        )
        return
    if file_type not in VALID_TYPES:
        result.error(
            filepath, "R1", f"Invalid type: '{file_type}' (expected: {sorted(VALID_TYPES)})"
        )
        return

    if file_type == "derived":
        if not header.get("source"):
            result.error(filepath, "R3", "Derived file missing 'source' declaration")
        sync = header.get("sync", "").lower()
        if sync not in VALID_SYNCS:
            result.error(
                filepath, "R3", f"Invalid sync: '{sync}' (expected: {VALID_SYNCS})"
            )
        sla = header.get("sla", "").lower()
        if sla not in VALID_SLAS:
            result.error(
                filepath, "R4", f"Invalid SLA: '{sla}' (expected: {VALID_SLAS})"
            )

    if file_type == "frozen":
        sla = header.get("sla", "none").lower()
        if sla != "none":
            result.warn(filepath, "R4", "Frozen files should have sla: none")

    result.ok()


def check_duplicate_canonicals(managed_files, result):
    """Rule 2: No duplicate canonicals for same content domain."""
    canonicals = {}
    for fp in managed_files:
        header, _ = parse_header(fp)
        if header and header.get("type", "").lower() == "canonical":
            name = Path(fp).name
            canonicals.setdefault(name, []).append(fp)

    for name, paths in canonicals.items():
        if len(paths) > 1:
            for p in paths:
                result.error(
                    p,
                    "R2",
                    f"Duplicate canonical: {name} also at "
                    f"{[x for x in paths if x != p]}",
                )


def repo_domain(root):
    """Read the repo's own domain from service-metadata.yaml.

    Returns None if the file is absent or unreadable. Mapping:
        service type: governance -> domain: organization
        service type: product    -> domain: product
        service type: infra      -> domain: infrastructure
        service type: workspace  -> domain: workspace
    Anything else returns None and disables the R6 check.
    """
    meta = Path(root) / "service-metadata.yaml"
    if not meta.exists() or yaml is None:
        return None
    try:
        data = yaml.safe_load(meta.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return None
    mapping = {
        "governance": "organization",
        "org": "organization",
        "product": "product",
        "infra": "infrastructure",
        "infrastructure": "infrastructure",
        "workspace": "workspace",
    }
    return mapping.get(str(data.get("type", "")).strip().lower())


def check_domain_boundaries(managed_files, result, root):
    """Rule 6: Every file belongs to exactly one domain boundary.

    Opt-in via explicit `domain:` frontmatter. When a file declares a domain
    that does not match the repo's own service-metadata domain, it is a
    cross-domain leak. Same opt-in pattern as R7 -- historical files without
    `domain:` are not retroactively classified.
    """
    repo_dom = repo_domain(root)
    if repo_dom is None:
        return
    allowed = {repo_dom, "workspace"}
    for fp in managed_files:
        header, _ = parse_header(fp)
        if not header:
            continue
        declared = (header.get("domain") or "").strip().lower()
        if not declared:
            continue
        if declared not in allowed:
            result.error(
                fp,
                "R6",
                f"File declares domain '{declared}' but lives in a '{repo_dom}' repo (cross-domain leak)",
            )


def workflow_trigger_paths(workflows_dir):
    """Return the union of path patterns across all workflow push/pull_request triggers."""
    if not workflows_dir.exists() or yaml is None:
        return set()
    patterns: set[str] = set()
    for wf in sorted(workflows_dir.glob("*.yml")) + sorted(workflows_dir.glob("*.yaml")):
        try:
            data = yaml.safe_load(wf.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        # PyYAML parses the `on:` key as boolean True for unquoted YAML. Handle both.
        on_block = data.get("on") or data.get(True)
        if not isinstance(on_block, dict):
            continue
        for event in ("push", "pull_request"):
            event_block = on_block.get(event)
            if not isinstance(event_block, dict):
                continue
            for key in ("paths", "paths-ignore"):
                paths = event_block.get(key)
                if isinstance(paths, list):
                    patterns.update(str(p) for p in paths)
    return patterns


def _path_covered(source_path, patterns):
    """Return True if any workflow path pattern plausibly covers source_path.

    This is approximate: we treat `**` as a wildcard and check prefix/suffix
    match against the literal source path. False negatives here are fine
    because the SLA check emits warnings only.
    """
    if not source_path or not patterns:
        return False
    from fnmatch import fnmatch
    for pattern in patterns:
        pat = pattern.replace("**/", "*/").replace("**", "*")
        if fnmatch(source_path, pat) or fnmatch(source_path, pattern):
            return True
        # Directory-prefix shorthand: `foo/**` covers everything under foo/.
        if pattern.endswith("/**") and source_path.startswith(pattern[:-3] + "/"):
            return True
        if pattern.endswith("/*") and source_path.startswith(pattern[:-2] + "/"):
            return True
    return False


def check_sla_ci_wiring(managed_files, result, root):
    """Derived files with sync: ci and tight SLAs must have a matching workflow trigger.

    A warning, not an error: path glob semantics differ between GitHub Actions
    and fnmatch, so false negatives are expected. The signal is still useful
    because a derived file with sync: ci and NO matching path pattern across
    any workflow is almost certainly un-wired.
    """
    patterns = workflow_trigger_paths(Path(root) / ".github" / "workflows")
    if not patterns:
        return
    for fp in managed_files:
        header, _ = parse_header(fp)
        if not header:
            continue
        if header.get("type", "").lower() != "derived":
            continue
        sync = header.get("sync", "").lower()
        sla = header.get("sla", "").lower()
        if sync != "ci":
            continue
        if sla not in {"realtime", "on-change"}:
            continue
        source = (header.get("source") or "").strip()
        if not source or source == "none":
            continue
        # `source` may be a path, a comma/space separated list, or a description.
        # Extract tokens that look like repo-relative paths.
        candidates = [tok.strip() for tok in re.split(r"[,\s]+", source) if "/" in tok or tok.endswith((".md", ".json", ".yaml", ".yml"))]
        if not candidates:
            continue
        covered = any(_path_covered(cand, patterns) for cand in candidates)
        if not covered:
            result.warn(
                fp,
                "R4",
                f"sync=ci sla={sla} but no workflow trigger matches source '{source}'",
            )


def check_dual_sources(managed_files, result):
    """Rule 7: Canonical vs derived must be explicit across the domain.

    R2 catches two files with the same filename both claiming canonical. R7
    is broader: two differently-named files both claiming canonical over the
    same content domain. This check is opt-in -- only files that declare an
    explicit `domain:` frontmatter key participate, which lets new files
    assert their domain without forcing a retroactive classification pass on
    historical docs.
    """
    by_domain: dict[str, list[str]] = {}
    for fp in managed_files:
        header, _ = parse_header(fp)
        if not header:
            continue
        if header.get("type", "").lower() != "canonical":
            continue
        domain = (header.get("domain") or "").strip().lower()
        if not domain:
            continue
        by_domain.setdefault(domain, []).append(fp)

    for domain, paths in by_domain.items():
        if len(paths) <= 1:
            continue
        for p in paths:
            others = [x for x in paths if x != p]
            result.error(
                p,
                "R7",
                f"Multiple canonicals declare domain '{domain}': also {others}",
            )


def check_zombies(managed_files, all_contents, result):
    """Rule 9: Detect zombie files."""
    for fp in managed_files:
        header, _ = parse_header(fp)
        if header is None:
            continue
        file_type = header.get("type", "").lower()
        if file_type in ("canonical", "generated", "frozen"):
            continue
        # For derived files, check if referenced somewhere
        name = Path(fp).name
        referenced = any(
            name in content for path, content in all_contents.items() if path != fp
        )
        if not referenced:
            result.warn(
                fp,
                "R9",
                "Potential zombie: derived/unknown file not referenced anywhere",
            )


def check_staleness(managed_files, result):
    """Rule 10: Managed governance docs must have last_updated within 90 days.

    Emits a warning (not an error) on initial rollout. The grace period is
    30 days from 2026-04-25; after 2026-05-25 the warning converts to an error.
    """
    GRACE_PERIOD_END = date(2026, 5, 25)
    MAX_AGE_DAYS = 90
    today = date.today()
    grace_active = today <= GRACE_PERIOD_END

    for fp in managed_files:
        path = Path(fp)

        # Only apply to docs/**/*.md (managed governance class). Skip archive.
        parts = path.parts
        if "archive" in parts:
            continue
        if not any(p == "docs" for p in parts):
            continue
        if path.suffix != ".md":
            continue

        header, _ = parse_header(fp)
        if not header:
            continue

        # Only files with last_updated are in scope — others already fail R1/R4.
        raw_date = header.get("last_updated", "").strip()
        if not raw_date:
            continue

        # Parse ISO date. Accept YYYY-MM-DD only.
        try:
            doc_date = date.fromisoformat(raw_date)
        except ValueError:
            result.warn(fp, "R10", f"last_updated '{raw_date}' is not a valid ISO date (YYYY-MM-DD)")
            continue

        age_days = (today - doc_date).days
        if age_days > MAX_AGE_DAYS:
            msg = (
                f"last_updated is {age_days} days old (limit: {MAX_AGE_DAYS}). "
                f"Review and update this doc, or move to docs/archive/ if complete."
            )
            if grace_active:
                result.warn(fp, "R10", msg)
            else:
                result.error(fp, "R10", msg)


def validate(root, ci_mode=False):
    """Run all validation checks."""
    result = ValidationResult()
    root = Path(root).resolve()
    managed_files = []
    all_contents = {}

    # Directories to always skip (build artifacts, environments, caches)
    SKIP_DIRS = {
        "node_modules",
        "__pycache__",
        "dist",
        "build",
        ".venv",
        "venv",
        ".next",
        ".turbo",
        "coverage",
        "playwright-report",
        "test-results",
        "state",
        # External platform tooling — governed by its own standards, not alawein doc doctrine
        "claude-agent-platform",
    }

    for dirpath, dirnames, filenames in os.walk(root):
        # Skip hidden dirs, build dirs, and known non-doc directories
        dirnames[:] = [
            d
            for d in dirnames
            if not d.startswith(".") and d not in SKIP_DIRS
        ]

        for d in dirnames:
            check_directory_naming(os.path.join(dirpath, d), result)

        for f in filenames:
            fp = os.path.join(dirpath, f)
            check_naming(fp, result)

            if Path(f).suffix in MANAGED_EXTENSIONS:
                managed_files.append(fp)
                try:
                    with open(fp, "r", encoding="utf-8") as fh:
                        all_contents[fp] = fh.read()
                except (UnicodeDecodeError, PermissionError):
                    pass

    for fp in managed_files:
        check_header(fp, result, root)

    check_duplicate_canonicals(managed_files, result)
    check_dual_sources(managed_files, result)
    check_domain_boundaries(managed_files, result, root)
    check_sla_ci_wiring(managed_files, result, root)
    check_zombies(managed_files, all_contents, result)
    check_staleness(managed_files, result)

    success = result.report()
    if ci_mode and not success:
        sys.exit(1)
    return success


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Docs Doctrine Validator")
    parser.add_argument("path", nargs="?", default=".", help="Directory to validate")
    parser.add_argument(
        "--ci", action="store_true", help="CI mode: exit 1 on failure"
    )
    parser.add_argument(
        "--fix", action="store_true", help="Interactive fix mode (not yet implemented)"
    )
    args = parser.parse_args()

    validate(args.path, ci_mode=args.ci)
