#!/usr/bin/env python3
"""Enforce the alawein/CLAUDE.md hard constraint against AI attribution.

CLAUDE.md hard constraint #2 forbids AI attribution in commits, code
comments, and documentation. Scans managed markdown, prompt-kits, and root
canonical docs for attribution phrases. This script targets documentation
only; commit-message enforcement belongs in a commit-msg git hook, not CI,
because CI sees history after it has already been authored.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

# Regex patterns (case-insensitive). Keep this list narrow to avoid false
# positives on legitimate discussion of AI tooling in governance docs.
PATTERNS = [
    (re.compile(r"Co-Authored-By:\s*Claude", re.IGNORECASE), "Co-Authored-By: Claude trailer"),
    (re.compile(r"Co-Authored-By:\s*ChatGPT", re.IGNORECASE), "Co-Authored-By: ChatGPT trailer"),
    (re.compile(r"Co-Authored-By:\s*Copilot", re.IGNORECASE), "Co-Authored-By: Copilot trailer"),
    (re.compile(r"Generated with \[?Claude Code", re.IGNORECASE), "Generated with Claude Code attribution"),
    (re.compile(r"Generated by Claude", re.IGNORECASE), "Generated by Claude attribution"),
    (re.compile(r"🤖\s*Generated with", re.IGNORECASE), "robot-emoji generation attribution"),
    (re.compile(r"<noreply@anthropic\.com>", re.IGNORECASE), "Anthropic noreply co-author email"),
]

# Files that legitimately document the anti-pattern (e.g., this script and
# governance docs that quote the forbidden phrases). Exempt by exact repo-
# relative path.
EXEMPT_PATHS = {
    "scripts/validate-no-ai-attribution.py",
    "CLAUDE.md",
    "AGENTS.md",
    ".claude/CLAUDE.md",
    ".claude/AGENTS.md",
}

# Directory prefixes that are skipped entirely (archive, build artifacts).
SKIP_PREFIXES = (
    "docs/archive/",
    "node_modules/",
    ".venv/",
    "venv/",
    "dist/",
    "build/",
    ".next/",
    ".turbo/",
    ".git/",
)

SCAN_SUFFIXES = {".md", ".mdx", ".txt"}


def iter_scan_paths() -> list[Path]:
    paths: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix not in SCAN_SUFFIXES:
            continue
        rel = path.relative_to(ROOT).as_posix()
        if rel in EXEMPT_PATHS:
            continue
        if any(rel.startswith(prefix) for prefix in SKIP_PREFIXES):
            continue
        paths.append(path)
    return paths


def scan_file(path: Path) -> list[str]:
    rel = path.relative_to(ROOT).as_posix()
    errors: list[str] = []
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, PermissionError):
        return errors
    for line_no, line in enumerate(text.splitlines(), start=1):
        for pattern, label in PATTERNS:
            if pattern.search(line):
                errors.append(f"{rel}:{line_no}: forbidden attribution ({label})")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Scan for AI attribution in managed docs")
    parser.add_argument(
        "paths",
        nargs="*",
        help="Optional list of specific files to scan (relative to repo root).",
    )
    args = parser.parse_args(argv)

    if args.paths:
        targets = [ROOT / p for p in args.paths if (ROOT / p).is_file()]
    else:
        targets = iter_scan_paths()

    errors: list[str] = []
    for path in targets:
        errors.extend(scan_file(path))

    if errors:
        for err in errors:
            print(err, file=sys.stderr)
        print(
            f"\nAI-attribution scan failed with {len(errors)} violation(s).",
            file=sys.stderr,
        )
        return 1

    print(f"AI-attribution scan passed ({len(targets)} file(s) scanned).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
