#!/usr/bin/env python3
"""Style validator for governed Alawein surfaces."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

DEFAULT_ROOT = Path(__file__).resolve().parent.parent.parent

SKIP_DIRS = {
    ".git",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
    ".next",
    ".turbo",
    "coverage",
    "playwright-report",
    "test-results",
    "state",
}
# docs/archive/ and docs/internal/ are exempt from doctrine CI (CLAUDE.md rule
# 11). claude-agent-platform/ mirrors ~/.claude and carries vendored
# third-party skills; it is not an authored fleet-governed doc surface.
SKIP_PATH_PREFIXES = ("docs/archive/", "docs/internal/", "claude-agent-platform/")
SKIP_GENERATED_MARKERS = (
    "# AUTO-GENERATED",
    "# This file is generated",
    "<!-- AUTO-GENERATED -->",
    "<!-- generated by",
    "<!-- Generated by scripts/sync-readme.py.",
)

# Kept in sync with the banned register in docs/style/VOICE.md (source:
# ~/.claude/voice-and-style.md). One pattern per banned word or phrase.
FORBIDDEN_REGISTER = [
    r"\bpassionate about\b",
    r"\bleverages?\b",
    r"\bleveraging\b",
    r"\binnovative\b",
    r"\bcutting-edge\b",
    r"\bcomprehensive\b",
    r"\bexcited to\b",
    r"\bit'?s worth noting\b",
    r"\binterestingly\b",
    r"\bdelv(?:e|es|ed|ing)\b",
    r"\bdeep dive\b",
    r"\butilize\b",
    r"\bin today'?s world\b",
    r"\bmoving forward\b",
    r"\bmoreover\b",
    r"\bfurthermore\b",
    r"\bsynergy\b",
    r"\bholistic\b",
    r"\bgame-changing\b",
    r"\bgroundbreaking\b",
    r"\bseamless\b",
    r"\bseamlessly\b",
    r"\bstreamlin(?:e|es|ed|ing)\b",
    r"\brobust\b",
    r"\bpowerful\b",
    r"\bempower\b",
    r"\btransformative\b",
    r"\bthat being said\b",
    r"\bI am pleased to\b",
    r"\bI hope this helps\b",
    r"\bfeel free to\b",
    r"\bas mentioned above\b",
]
AI_ATTRIBUTION_PATTERNS = [
    r"Generated with Claude",
    r"Co-Authored-By: Claude",
    r"Generated by (Claude|ChatGPT|OpenAI|Anthropic)",
    r"\bAI-generated\s+(?:with|by|via)\b",
]
STALE_IDENTITY_PATTERNS = [
    r"\balaweimm90\b",
    r"\bmalawein\.com\b",
]
FORBIDDEN_PERSONAL_CLAIMS = [
    # Phrases contradicting canonical personal facts. Update when a fact
    # changes; the stale phrasing moves here. Source of truth:
    # docs/style/terminology-registry.yaml :: forbidden_personal_claims.
    r"\bPh\.?D\.? candidate\b",
    r"\bfinishing (my|a) PhD\b",
    r"\bpursuing (my|a) PhD\b",
    r"\bABD\b",
]
FRONTMATTER_RE = re.compile(r"\A---\s*\r?\n.*?\r?\n---\s*(?:\r?\n|$)", re.DOTALL)

# D1: em-dashes (U+2014) are prohibited on governed surfaces. Use commas,
# parentheses, or sentence breaks. The rule blocks on Blocking surfaces and
# warns elsewhere. Source of truth: docs/style/VOICE.md :: Punctuation
# discipline. The en-dash (U+2013) is intentionally not covered here; numeric
# ranges (12-20) and date ranges legitimately use it.
EM_DASH = "—"
FENCE_RE = re.compile(r"^\s*```")

# Docs that legitimately quote the banned register (the voice contract itself,
# audit READMEs, design-defense docs) wrap the quoted block in these sentinels.
# Sentinels inside fenced code blocks do not toggle. Nesting is not supported.
# Source: docs/internal/issues/2026-05-11-voice-check-ignore-sentinels.md.
IGNORE_START = "<!-- voice-check:ignore-start -->"
IGNORE_END = "<!-- voice-check:ignore-end -->"


@dataclass
class Violation:
    path: Path
    line: int
    rule: str
    detail: str
    tier: Literal["blocking", "advisory"]

    def __str__(self) -> str:
        label = "BLOCK" if self.tier == "blocking" else "WARN "
        return f"[{label}] {self.path}:{self.line} - {self.rule}: {self.detail}"


@dataclass
class Report:
    violations: list[Violation] = field(default_factory=list)

    def add(self, violation: Violation) -> None:
        self.violations.append(violation)

    @property
    def blocking(self) -> list[Violation]:
        return [v for v in self.violations if v.tier == "blocking"]

    @property
    def advisory(self) -> list[Violation]:
        return [v for v in self.violations if v.tier == "advisory"]

    def print_summary(self) -> None:
        if not self.violations:
            print("OK - no violations found.")
            return
        for violation in self.violations:
            print(violation)
        print()
        print(f"Summary: {len(self.blocking)} blocking, {len(self.advisory)} advisory")


def should_skip(path: Path, root: Path) -> bool:
    rel = path.relative_to(root).as_posix()
    if any(part in SKIP_DIRS for part in path.parts):
        return True
    return rel.startswith(SKIP_PATH_PREFIXES)


def is_generated(content: str) -> bool:
    head = content[:512].lower()
    return any(marker.lower() in head for marker in SKIP_GENERATED_MARKERS)


def is_blocking_surface(path: Path, root: Path | None = None) -> bool:
    # With a root, Blocking is exactly the pre-2026-07 gate set: the root
    # README/CLAUDE/AGENTS, docs/README, and prompt-kits/. Nested copies of
    # those filenames (package READMEs, vendored AGENTS.md) are advisory, so
    # widening the scan does not turn fleet doctrine CI red overnight.
    if root is not None:
        try:
            rel_to_root = path.relative_to(root).as_posix()
        except ValueError:
            rel_to_root = None
        if rel_to_root is not None:
            if rel_to_root in {"README.md", "docs/README.md", "CLAUDE.md", "AGENTS.md"}:
                return True
            return rel_to_root.startswith("prompt-kits/")
    rel = path.as_posix()
    if path.name == "README.md":
        return True
    if path.name in {"CLAUDE.md", "AGENTS.md"}:
        return True
    return "/prompt-kits/" in f"/{rel}/"


def collect_paths(root: Path) -> list[Path]:
    # Every non-exempt markdown file is a governed surface (VOICE.md); rules
    # block on Blocking surfaces (README/CLAUDE/AGENTS/prompt-kits) and warn
    # elsewhere. Exemptions: SKIP_DIRS, docs/archive/, docs/internal/, and
    # generated files.
    candidates: list[Path] = []
    for pattern in ("README.md", "docs/README.md", "CLAUDE.md", "AGENTS.md", "prompt-kits/*.md"):
        candidates.extend(root.glob(pattern))
    for path in root.rglob("*.md"):
        if should_skip(path, root):
            continue
        rel = path.relative_to(root).as_posix()
        if rel in {"README.md", "docs/README.md", "CLAUDE.md", "AGENTS.md"}:
            continue
        candidates.append(path)
    unique: dict[str, Path] = {}
    for path in candidates:
        if should_skip(path, root):
            continue
        unique[path.resolve().as_posix()] = path.resolve()
    return sorted(unique.values())


def ignored_line_set(content: str) -> tuple[set[int], int]:
    """Line numbers inside voice-check ignore regions, plus the line of an
    unterminated ignore-start (0 if none). Sentinels inside fenced code blocks
    do not toggle; the sentinel lines themselves are ignored too."""
    ignored: set[int] = set()
    in_fence = False
    ignoring = False
    ignore_start_line = 0
    for line_no, line in enumerate(content.splitlines(), start=1):
        if FENCE_RE.match(line):
            in_fence = not in_fence
        stripped = line.strip()
        if not in_fence:
            if stripped == IGNORE_START:
                ignoring = True
                ignore_start_line = line_no
                ignored.add(line_no)
                continue
            if stripped == IGNORE_END:
                ignoring = False
                ignored.add(line_no)
                continue
        if ignoring:
            ignored.add(line_no)
    return ignored, (ignore_start_line if ignoring else 0)


def add_match_violations(
    report: Report,
    path: Path,
    content: str,
    patterns: list[str],
    rule: str,
    tier: Literal["blocking", "advisory"],
    ignored: set[int] | None = None,
) -> None:
    for line_no, line in enumerate(content.splitlines(), start=1):
        if ignored and line_no in ignored:
            continue
        for pattern in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                report.add(
                    Violation(
                        path=path,
                        line=line_no,
                        rule=rule,
                        detail=line.strip()[:160],
                        tier=tier,
                    )
                )


def check_frontmatter(path: Path, content: str, report: Report, root: Path | None = None) -> None:
    # GitHub-facing README surfaces only: the root README and docs/README.
    # Nested READMEs (templates/, packages/) carry doc-contract frontmatter
    # legitimately.
    rel = path.as_posix()
    if root is not None:
        try:
            rel_to_root = path.relative_to(root).as_posix()
        except ValueError:
            rel_to_root = rel
        if rel_to_root not in {"README.md", "docs/README.md"}:
            return
    if rel.endswith("README.md") and FRONTMATTER_RE.match(content):
        report.add(
            Violation(
                path=path,
                line=1,
                rule="frontmatter",
                detail="YAML frontmatter found in a GitHub-facing README surface",
                tier="blocking",
            )
        )


def check_emdash(path: Path, content: str, report: Report, root: Path | None = None) -> None:
    """D1: flag em-dashes (U+2014) outside fenced code blocks.

    Blocking on Blocking surfaces (README/CLAUDE/AGENTS/prompt-kits), advisory
    elsewhere. Fenced code blocks are skipped so quoted bad examples and shell
    snippets do not trip the gate.
    """
    tier: Literal["blocking", "advisory"] = (
        "blocking" if is_blocking_surface(path, root) else "advisory"
    )
    in_fence = False
    for line_no, line in enumerate(content.splitlines(), start=1):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if EM_DASH in line:
            report.add(
                Violation(
                    path=path,
                    line=line_no,
                    rule="em-dash",
                    detail=line.strip()[:160],
                    tier=tier,
                )
            )


def run_checks(
    paths: list[Path],
    checks: set[str],
    report: Report,
    root: Path | None = None,
) -> None:
    for path in paths:
        try:
            content = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, PermissionError):
            continue
        if is_generated(content):
            continue

        ignored, unterminated_line = ignored_line_set(content)
        if unterminated_line:
            report.add(
                Violation(
                    path=path,
                    line=unterminated_line,
                    rule="ignore-sentinel",
                    detail="voice-check:ignore-start is never closed",
                    tier="advisory",
                )
            )

        if "frontmatter" in checks:
            check_frontmatter(path, content, report, root=root)

        if "emdash" in checks:
            check_emdash(path, content, report, root=root)

        if "voice" in checks:
            add_match_violations(
                report,
                path,
                content,
                FORBIDDEN_REGISTER,
                "forbidden-register",
                "blocking" if is_blocking_surface(path, root) else "advisory",
                ignored=ignored,
            )

        if "attribution" in checks:
            add_match_violations(
                report,
                path,
                content,
                AI_ATTRIBUTION_PATTERNS,
                "ai-attribution",
                "blocking" if is_blocking_surface(path, root) else "advisory",
                ignored=ignored,
            )

        if "identity" in checks:
            add_match_violations(
                report,
                path,
                content,
                STALE_IDENTITY_PATTERNS,
                "stale-identity",
                "blocking" if is_blocking_surface(path, root) else "advisory",
                ignored=ignored,
            )

        if "claim" in checks:
            add_match_violations(
                report,
                path,
                content,
                FORBIDDEN_PERSONAL_CLAIMS,
                "stale-claim",
                "blocking" if is_blocking_surface(path, root) else "advisory",
                ignored=ignored,
            )


def main() -> int:
    # Violations quote file content; Windows consoles default to cp1252.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description="Validate governed style surfaces")
    parser.add_argument(
        "--check",
        choices=["frontmatter", "emdash", "voice", "attribution", "identity", "claim", "all"],
        default="all",
    )
    parser.add_argument("--paths", nargs="*", help="Specific file paths to check")
    parser.add_argument("--root", default=str(DEFAULT_ROOT), help="Repository root to scan")
    parser.add_argument("--ci", action="store_true", help="Exit non-zero on blocking violations")
    args = parser.parse_args()

    checks = {"frontmatter", "emdash", "voice", "attribution", "identity", "claim"} if args.check == "all" else {args.check}
    root = Path(args.root).resolve()

    if args.paths:
        paths = [Path(p).resolve() for p in args.paths]
    else:
        paths = collect_paths(root)

    report = Report()
    run_checks(paths, checks, report, root=root)
    report.print_summary()

    if args.ci and report.blocking:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
