name: Access Request
description: Request repository or resource access
title: "[ACCESS] "
labels: ["access-request", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Access Request Form
        Please fill out this form to request access to repositories or resources.

  - type: dropdown
    id: access-type
    attributes:
      label: Access Type
      description: What type of access do you need?
      options:
        - Repository Read (readonly)
        - Repository Write (developer)
        - Code Review (reviewer)
        - Admin Access (admin)
        - Contractor Access (contractor)
    validations:
      required: true

  - type: input
    id: resource
    attributes:
      label: Resource
      description: Which repository or resource do you need access to?
      placeholder: "e.g., platforms/repz, packages/ui"
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Business Justification
      description: Why do you need this access?
      placeholder: |
        Please explain:
        - What project or task requires this access
        - Why existing access is insufficient
        - Expected duration of need
    validations:
      required: true

  - type: dropdown
    id: duration
    attributes:
      label: Duration
      description: How long do you need this access?
      options:
        - Permanent
        - 90 days
        - 30 days
        - 1 week
        - One-time task
    validations:
      required: true

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      options:
        - label: I understand that access will be audited and logged
          required: true
        - label: I will follow the organization's security policies
          required: true
        - label: I will report any security concerns immediately
          required: true
