name: "📚 Quarterly Documentation Audit"
description: "Template for quarterly documentation review and quality assurance"
title: "[DOCS AUDIT] Q{quarter} {year} Documentation Review"
labels: ["documentation", "audit", "quarterly"]
assignees:
  - alawein

body:
  - type: markdown
    attributes:
      value: |
        ## Quarterly Documentation Audit

        This template guides the quarterly documentation review process.
        Complete each section to ensure documentation quality and freshness.

  - type: input
    id: quarter
    attributes:
      label: Quarter
      description: Which quarter is this audit for?
      placeholder: "Q1 2025"
    validations:
      required: true

  - type: input
    id: auditor
    attributes:
      label: Auditor
      description: Who is performing this audit?
      placeholder: "@username"
    validations:
      required: true

  - type: checkboxes
    id: content-quality
    attributes:
      label: "📝 Content Quality"
      description: "Verify documentation content is accurate and up-to-date"
      options:
        - label: All code examples have been tested and work correctly
        - label: No references to non-existent files or broken links
        - label: Terminology is consistent across all documentation
        - label: All screenshots and images are current
        - label: Version numbers and dependencies are accurate
        - label: API documentation matches actual endpoints

  - type: checkboxes
    id: structural-integrity
    attributes:
      label: "🏗️ Structural Integrity"
      description: "Verify documentation structure and organization"
      options:
        - label: All internal links are functional
        - label: All external links are valid and accessible
        - label: All images and assets are present and loading
        - label: File naming conventions are followed
        - label: Directory structure is logical and consistent
        - label: Table of contents are accurate

  - type: checkboxes
    id: freshness
    attributes:
      label: "🕐 Freshness"
      description: "Verify documentation is current"
      options:
        - label: All docs have last_verified date in frontmatter
        - label: Docs older than 90 days have been reviewed
        - label: Deprecated content has been archived
        - label: New features are documented
        - label: Removed features are no longer documented

  - type: checkboxes
    id: completeness
    attributes:
      label: "✅ Completeness"
      description: "Verify all required documentation exists"
      options:
        - label: README.md is comprehensive and current
        - label: CONTRIBUTING.md exists and is accurate
        - label: CODE_OF_CONDUCT.md exists
        - label: CHANGELOG.md is up to date
        - label: All platforms have documentation
        - label: API endpoints are fully documented

  - type: checkboxes
    id: accessibility
    attributes:
      label: "♿ Accessibility"
      description: "Verify documentation is accessible"
      options:
        - label: All images have alt text
        - label: Code blocks have language specified
        - label: Headings follow proper hierarchy
        - label: Links have descriptive text
        - label: Tables have headers

  - type: textarea
    id: issues-found
    attributes:
      label: "🐛 Issues Found"
      description: "List any issues discovered during the audit"
      placeholder: |
        - [ ] Issue 1: Description
        - [ ] Issue 2: Description
        - [ ] Issue 3: Description

  - type: textarea
    id: improvements
    attributes:
      label: "💡 Suggested Improvements"
      description: "List any suggested improvements or enhancements"
      placeholder: |
        - Suggestion 1
        - Suggestion 2

  - type: textarea
    id: notes
    attributes:
      label: "📋 Additional Notes"
      description: "Any other observations or notes from the audit"

  - type: checkboxes
    id: sign-off
    attributes:
      label: "✍️ Sign-off"
      description: "Confirm audit completion"
      options:
        - label: I have completed all sections of this audit
        - label: All critical issues have been logged
        - label: Follow-up tasks have been created for issues found
