name: RFC (Request for Comments)
description: Propose a significant change or new feature
title: "[RFC] "
labels: ["rfc", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Request for Comments
        Use this template for proposing significant changes to architecture,
        new features, or breaking changes.

  - type: input
    id: title
    attributes:
      label: RFC Title
      description: A short, descriptive title for your proposal
      placeholder: "RFC-XXXX: Short descriptive title"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One paragraph explaining the proposal
      placeholder: "Briefly describe what you're proposing and why"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change needed? What problem does it solve?
      placeholder: |
        - What is the current problem?
        - Who is affected?
        - What happens if we don't make this change?
    validations:
      required: true

  - type: textarea
    id: design
    attributes:
      label: Detailed Design
      description: Technical details of the proposal
      placeholder: |
        Describe the technical implementation:
        - Architecture changes
        - API changes
        - Data model changes
        - Dependencies
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches were considered?
      placeholder: |
        - Alternative 1: Description and why it was rejected
        - Alternative 2: Description and why it was rejected

  - type: textarea
    id: impact
    attributes:
      label: Impact Analysis
      description: Analyze the impact of this change
      placeholder: |
        - Breaking changes: Yes/No
        - Migration required: Yes/No
        - Performance impact: Positive/Negative/Neutral
        - Security implications: Describe any security considerations
        - Documentation updates: What docs need updating?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this change?
      options:
        - P0 - Critical (blocking release)
        - P1 - High (important for next release)
        - P2 - Medium (nice to have)
        - P3 - Low (future consideration)
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What areas does this affect?
      multiple: true
      options:
        - Architecture
        - API
        - Database
        - Security
        - Performance
        - UI/UX
        - Documentation
        - DevOps/Infrastructure
        - Testing

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing RFCs on this topic
          required: true
        - label: I have considered backward compatibility
          required: true
        - label: I am willing to implement this change (or help find someone)
          required: false
