#!/bin/bash

# REPZ Platform - Integration Setup Script
# Interactive script to configure all API integrations

set -e

echo "🔧 REPZ Platform - Integration Setup Wizard"
echo "==========================================="
echo ""
echo "This wizard will help you set up all third-party integrations."
echo "Have your API credentials ready!"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check if vercel CLI is available
USING_VERCEL=false
if command -v vercel &> /dev/null; then
    echo -e "${GREEN}✅ Vercel CLI detected${NC}"
    read -p "Do you want to add environment variables to Vercel? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        USING_VERCEL=true
    fi
else
    echo -e "${YELLOW}⚠️  Vercel CLI not found. Variables will only be saved locally.${NC}"
fi
echo ""

# Function to add environment variable
add_env_var() {
    local var_name=$1
    local var_description=$2
    local is_secret=${3:-true}

    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${YELLOW}$var_description${NC}"

    if [ "$is_secret" = true ]; then
        read -sp "Enter $var_name: " var_value
        echo
    else
        read -p "Enter $var_name: " var_value
    fi

    if [ -n "$var_value" ]; then
        echo "export $var_name=\"$var_value\"" >> .env.production.local

        if [ "$USING_VERCEL" = true ]; then
            echo "$var_value" | vercel env add $var_name production
            echo -e "${GREEN}✅ Added to Vercel${NC}"
        fi
    else
        echo -e "${YELLOW}⚠️  Skipped (empty value)${NC}"
    fi
    echo ""
}

# Create/clear the local env file
> .env.production.local
echo "# Generated by setup-integrations.sh on $(date)" >> .env.production.local
echo "" >> .env.production.local

echo "🎯 SUPABASE CONFIGURATION"
echo "Get these from: https://supabase.com/dashboard/project/_/settings/api"
add_env_var "VITE_SUPABASE_URL" "Supabase Project URL" false
add_env_var "VITE_SUPABASE_ANON_KEY" "Supabase Anon Key" true

echo "💳 STRIPE CONFIGURATION"
echo "Get these from: https://dashboard.stripe.com/apikeys"
add_env_var "VITE_STRIPE_PUBLIC_KEY" "Stripe Publishable Key (pk_live_...)" false
add_env_var "STRIPE_SECRET_KEY" "Stripe Secret Key (sk_live_...)" true

echo "💪 WHOOP INTEGRATION"
echo "Get these from: https://developer.whoop.com"
read -p "Do you want to configure Whoop? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    add_env_var "VITE_WHOOP_CLIENT_ID" "Whoop Client ID" false
    add_env_var "VITE_WHOOP_CLIENT_SECRET" "Whoop Client Secret" true
fi

echo "📅 GOOGLE CALENDAR INTEGRATION"
echo "Get these from: https://console.cloud.google.com/apis/credentials"
read -p "Do you want to configure Google Calendar? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    add_env_var "VITE_GOOGLE_CLIENT_ID" "Google Client ID" false
    add_env_var "VITE_GOOGLE_CLIENT_SECRET" "Google Client Secret" true
fi

echo "🏃 STRAVA INTEGRATION"
echo "Get these from: https://www.strava.com/settings/api"
read -p "Do you want to configure Strava? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    add_env_var "VITE_STRAVA_CLIENT_ID" "Strava Client ID" false
    add_env_var "VITE_STRAVA_CLIENT_SECRET" "Strava Client Secret" true
fi

echo "🤖 OPENAI CONFIGURATION"
echo "Get this from: https://platform.openai.com/api-keys"
add_env_var "VITE_OPENAI_API_KEY" "OpenAI API Key (sk-...)" true

echo "📧 SENDGRID CONFIGURATION"
echo "Get this from: https://app.sendgrid.com/settings/api_keys"
read -p "Do you want to configure SendGrid? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    add_env_var "SENDGRID_API_KEY" "SendGrid API Key" true
    add_env_var "SENDGRID_FROM_EMAIL" "From Email Address" false
fi

echo "📊 SENTRY CONFIGURATION"
echo "Get this from: https://sentry.io/settings/projects/"
read -p "Do you want to configure Sentry? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    add_env_var "VITE_SENTRY_DSN" "Sentry DSN" false
fi

echo ""
echo -e "${GREEN}✅ Configuration complete!${NC}"
echo ""
echo "Environment variables saved to: .env.production.local"
echo ""
echo "Next steps:"
echo "1. Review the generated .env.production.local file"
echo "2. Deploy to Vercel: npm run deploy:production"
echo "3. Test all integrations"
echo ""
echo "⚠️  SECURITY: Never commit .env.production.local to git!"
