from __future__ import annotations

import sys
import unittest
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[1]
OPS_DIR = SCRIPTS_DIR / "ops"
for d in (str(SCRIPTS_DIR), str(OPS_DIR)):
    if d not in sys.path:
        sys.path.insert(0, d)

from build_voice_unified import (  # noqa: E402
    assemble,
    demote_headers,
    drop_leading_h1,
    strip_frontmatter,
)

FIXTURES = Path(__file__).parent / "fixtures" / "voice_unified"


class StripFrontmatterTests(unittest.TestCase):
    def test_strips_well_formed_frontmatter(self):
        text = "---\ntype: canonical\n---\n\n# Heading\n\nBody.\n"
        self.assertEqual(strip_frontmatter(text), "# Heading\n\nBody.\n")

    def test_no_frontmatter_returns_unchanged(self):
        text = "# Heading\n\nBody.\n"
        self.assertEqual(strip_frontmatter(text), text)

    def test_unterminated_frontmatter_returns_unchanged(self):
        text = "---\ntype: canonical\n\n# Heading\n"
        self.assertEqual(strip_frontmatter(text), text)


class DropLeadingH1Tests(unittest.TestCase):
    def test_drops_first_h1_line(self):
        text = "# Block A · Test\n\nBody.\n"
        self.assertEqual(drop_leading_h1(text), "Body.\n")

    def test_preserves_subtitle_after_h1(self):
        text = "# Block A · Test\n\n_Subtitle._\n\n## §1\n"
        self.assertEqual(drop_leading_h1(text), "_Subtitle._\n\n## §1\n")

    def test_no_h1_returns_unchanged(self):
        text = "## §1 First section\n\nBody.\n"
        self.assertEqual(drop_leading_h1(text), text)

    def test_h2_is_not_h1(self):
        text = "## Subsection\n\nBody.\n"
        self.assertEqual(drop_leading_h1(text), text)

    def test_blank_lines_before_h1_skipped(self):
        text = "\n\n# Block A · Test\n\nBody.\n"
        self.assertEqual(drop_leading_h1(text), "Body.\n")


class DemoteHeadersTests(unittest.TestCase):
    def test_h1_to_h2(self):
        self.assertEqual(demote_headers("# Title\n"), "## Title\n")

    def test_h2_to_h3(self):
        self.assertEqual(demote_headers("## Section\n"), "### Section\n")

    def test_h6_to_h7(self):
        self.assertEqual(demote_headers("###### Six\n"), "####### Six\n")

    def test_only_demotes_at_line_start(self):
        text = "Inline #foo and ## bar should not change.\n"
        self.assertEqual(demote_headers(text), text)

    def test_demotes_multiple_lines(self):
        text = "# H1\n\n## H2\n\n### H3\n"
        expected = "## H1\n\n### H2\n\n#### H3\n"
        self.assertEqual(demote_headers(text), expected)

    def test_preserves_content_after_hashes(self):
        self.assertEqual(demote_headers("## §7 Contribution\n"), "### §7 Contribution\n")

    def test_skips_inside_fenced_code_blocks(self):
        text = (
            "## Heading before fence\n"
            "\n"
            "```python\n"
            "# k-points must be in reduced coordinates\n"
            "## not a heading either\n"
            "```\n"
            "\n"
            "## Heading after fence\n"
        )
        expected = (
            "### Heading before fence\n"
            "\n"
            "```python\n"
            "# k-points must be in reduced coordinates\n"
            "## not a heading either\n"
            "```\n"
            "\n"
            "### Heading after fence\n"
        )
        self.assertEqual(demote_headers(text), expected)


class AssembleTests(unittest.TestCase):
    def test_assembles_two_fixtures_with_block_headers(self):
        blocks = [
            {
                "file": FIXTURES / "source_a.md",
                "title": "Block A · Test Block",
                "subtitle": "_Subtitle line for Block A._",
            },
            {
                "file": FIXTURES / "source_b.md",
                "title": "Block B · Another Test Block",
                "subtitle": None,
            },
        ]
        result = assemble(blocks, today="2026-05-11", last_updated="2026-05-11")

        self.assertIn("---\ntype: generated\n", result)
        self.assertIn("last_updated: 2026-05-11\n", result)
        self.assertIn("# Meshal Alawein — Voice Guide\n", result)
        self.assertIn("<!-- Generated by scripts/ops/build_voice_unified.py", result)

        self.assertIn("## Block A · Test Block\n", result)
        self.assertIn("_Subtitle line for Block A._\n", result)
        self.assertIn("## Block B · Another Test Block\n", result)

        self.assertIn("### §1 First section\n", result)
        self.assertIn("#### Subsection of §1\n", result)
        self.assertIn("### §3 Section three\n", result)

        self.assertNotIn("# Block A · Test Block\n\n", result)
        self.assertNotIn("# Block B · Another Test Block\n\n", result)

    def test_block_separator_between_blocks(self):
        blocks = [
            {
                "file": FIXTURES / "source_a.md",
                "title": "Block A · Test Block",
                "subtitle": None,
            },
            {
                "file": FIXTURES / "source_b.md",
                "title": "Block B · Another Test Block",
                "subtitle": None,
            },
        ]
        result = assemble(blocks, today="2026-05-11", last_updated="2026-05-11")
        self.assertIn("\n---\n\n## Block B", result)

    def test_idempotent(self):
        blocks = [
            {
                "file": FIXTURES / "source_a.md",
                "title": "Block A · Test Block",
                "subtitle": "_Subtitle line for Block A._",
            },
        ]
        first = assemble(blocks, today="2026-05-11", last_updated="2026-05-11")
        second = assemble(blocks, today="2026-05-11", last_updated="2026-05-11")
        self.assertEqual(first, second)


if __name__ == "__main__":
    unittest.main()
