import BirdLogoShowcase from '@/components/BirdLogoShowcase';
import Footer from '@/components/Footer';
import Navigation from '@/components/Navigation';
import ProductShowcase from '@/components/ProductShowcase';
import SEO from '@/components/SEO';

const Collection = () => {
  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: 'Live It Iconic Collection',
    description:
      'Explore our premium luxury automotive lifestyle apparel collection. Premium tees, caps, and hoodies designed with precision and refined aesthetics.',
    url: 'https://liveiticonic.com/collection',
    mainEntity: {
      '@type': 'ItemList',
      name: 'Premium Apparel Collection',
      description:
        'Curated selection of luxury athletic wear featuring geometric emblems and premium materials',
      numberOfItems: 3,
      itemListElement: [
        {
          '@type': 'Product',
          name: 'Premium Navy Tee with Gold Emblem',
          description: 'Luxury athletic tee featuring gold and champagne geometric emblem',
          image: '/mockups/tee-gold-navy.png',
          brand: {
            '@type': 'Brand',
            name: 'Live It Iconic',
          },
        },
        {
          '@type': 'Product',
          name: 'Structured Navy Cap with Embroidered Crest',
          description: 'Premium structured cap with embroidered hummingbird crest',
          image: '/mockups/cap-embroidery.png',
          brand: {
            '@type': 'Brand',
            name: 'Live It Iconic',
          },
        },
        {
          '@type': 'Product',
          name: 'Heavyweight Navy Hoodie',
          description: 'Premium heavyweight hoodie with emblem front and back',
          image: '/mockups/hoodie-back-front.png',
          brand: {
            '@type': 'Brand',
            name: 'Live It Iconic',
          },
        },
      ],
    },
  };

  return (
    <>
      <SEO
        title="Premium Collection | Live It Iconic"
        description="Explore our luxury automotive lifestyle apparel collection. Premium tees, caps, and hoodies designed with precision and refined aesthetics."
        canonical="/collection"
        structuredData={structuredData}
      />
      <div className="min-h-screen bg-lii-bg text-foreground font-ui overflow-x-hidden relative">
        <Navigation />
        <main>
          {/* Product mockups generated by AI */}
          <section className="pt-32 pb-10 container mx-auto px-6">
            <h1 className="text-3xl font-display tracking-tight text-lii-cloud mb-4">
              Product Preview
            </h1>
            <p className="text-lii-ash mb-6">Premium designs for tees, caps and hoodies.</p>
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <img
                src="/mockups/tee-gold-navy.png"
                alt="Premium navy tee with gold and champagne emblem"
                className="w-full h-auto rounded-2xl border border-lii-gold/20 bg-lii-ink/50"
                loading="lazy"
              />
              <img
                src="/mockups/cap-embroidery.png"
                alt="Structured navy cap with embroidered hummingbird crest"
                className="w-full h-auto rounded-2xl border border-lii-gold/20 bg-lii-ink/50"
                loading="lazy"
              />
              <img
                src="/mockups/hoodie-back-front.png"
                alt="Heavyweight navy hoodie with emblem front and back"
                className="w-full h-auto rounded-2xl border border-lii-gold/20 bg-lii-ink/50"
                loading="lazy"
              />
            </div>
          </section>

          {/* Bird Heritage Section */}
          <section className="py-16 bg-lii-ink">
            <div className="container mx-auto px-6">
              <div className="max-w-3xl mx-auto text-center mb-12">
                <h2 className="text-2xl sm:text-3xl font-display text-lii-gold mb-4">
                  Caribbean-Inspired Excellence
                </h2>
                <p className="text-lii-ash font-ui">
                  Each design embodies the spirit of Caribbean birds—grace, power, and freedom.
                </p>
              </div>
              <BirdLogoShowcase variant="carousel" />
            </div>
          </section>

          <ProductShowcase />
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Collection;
