// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbemxaykbjsbxlgfznwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZW14YXlrYmpzYnhsZ2Z6bnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTc2NjMsImV4cCI6MjA3MDIzMzY2M30.iiS6J96X7HQqMzGLKfaWLskKtqDHdvfku8DkekOB_vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});