#!/usr/bin/env bash
# generate-index.sh -- regenerates INDEX.md files from directory listings
# Part of Docs Doctrine (Phase 3: Introduce Generation)
#
# Usage:
#   ./scripts/generate-index.sh .                 # org repo only
#   ./scripts/generate-index.sh /path/to/repo     # specific repo
#   WORKSPACE=/path/to/ws ./scripts/generate-index.sh --all  # all workspace repos
set -euo pipefail

generate_index() {
  local docs_dir="$1"
  local repo_name="$2"

  local index_file="${docs_dir}/INDEX.md"
  local title="Index — ${repo_name}"

  {
    echo "---"
    echo "type: derived"
    echo "source: directory-structure"
    echo "sync: script"
    echo "sla: on-change"
    echo "---"
    echo ""
    echo "# ${title}"
    echo ""
    echo "> Auto-generated by \`generate-index.sh\`. Do not edit manually."
    echo ""
  } > "$index_file"

  # List top-level .md files (excluding INDEX.md itself)
  local has_top=false
  for f in "${docs_dir}"/*.md; do
    [ -f "$f" ] || continue
    local fname
    fname=$(basename "$f")
    [ "$fname" = "INDEX.md" ] && continue
    has_top=true
    echo "- [${fname}](${fname})" >> "$index_file"
  done
  $has_top && echo "" >> "$index_file"

  # List subdirectories with their contents
  for subdir in "${docs_dir}"/*/; do
    [ -d "$subdir" ] || continue
    local dirname
    dirname=$(basename "$subdir")
    # Skip hidden dirs
    [[ "$dirname" == .* ]] && continue

    local has_files=false
    for f in "${subdir}"/*.md; do
      [ -f "$f" ] || continue
      has_files=true
      break
    done
    $has_files || continue

    echo "## ${dirname}/" >> "$index_file"
    echo "" >> "$index_file"
    for f in "${subdir}"/*.md; do
      [ -f "$f" ] || continue
      local fname
      fname=$(basename "$f")
      echo "- [${fname}](${dirname}/${fname})" >> "$index_file"
    done
    echo "" >> "$index_file"
  done

  echo "Generated: ${index_file}"
}

if [ "${1:-}" = "--all" ]; then
  WORKSPACE="${WORKSPACE:-$(dirname "$(dirname "$(cd "$(dirname "$0")" && pwd)")")}"
  for repo_dir in "${WORKSPACE}"/*/; do
    [ -d "${repo_dir}/docs" ] || continue
    [ -d "${repo_dir}/.git" ] || continue
    repo_name=$(basename "$repo_dir")
    generate_index "${repo_dir}/docs" "$repo_name"
  done
else
  TARGET="${1:-.}"
  TARGET=$(cd "$TARGET" && pwd)
  if [ -d "${TARGET}/docs" ]; then
    repo_name=$(basename "$TARGET")
    generate_index "${TARGET}/docs" "$repo_name"
  else
    echo "No docs/ directory found in ${TARGET}"
    exit 1
  fi
fi
