#!/usr/bin/env python3
"""Generate the public profile README from canonical profile and project data."""

from __future__ import annotations

import sys
from pathlib import Path

from catalog_lib import load_catalogs, profile_config, repo_entries, repo_index_by_slug

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"

ACRONYMS = {"ai", "hpc", "llm", "api", "sdk", "ml", "ci", "cd", "sql", "os"}


def prettify_slug(slug: str) -> str:
    parts = [p for p in slug.split("-") if p]
    out: list[str] = []
    for i, p in enumerate(parts):
        if p.lower() in ACRONYMS:
            out.append(p.upper())
        elif i == 0:
            out.append(p.capitalize())
        else:
            out.append(p.lower())
    return " ".join(out)


def entry_url(entry: dict) -> str:
    url = (entry.get("homepage") or entry.get("url") or "").strip()
    if url:
        return url
    if entry.get("repo"):
        return f"https://github.com/{entry['repo']}"
    return ""


def render_link_row(profile: dict) -> str:
    urls = profile.get("urls") or {}
    ordered_keys = ("website", "morphism", "linkedin", "email")
    items: list[str] = []
    for key in ordered_keys:
        url = urls.get(key)
        if not url:
            continue
        display = url.replace("mailto:", "").removeprefix("https://").removeprefix("http://")
        display = display.removeprefix("www.")
        items.append(f"[{display}]({url})")
    return " · ".join(items)


def render_pins(profile: dict, repos: dict[str, dict]) -> list[str]:
    pins = profile.get("profile_pins") or []
    lines: list[str] = []
    for slug in pins:
        entry = repos.get(slug)
        if entry is None:
            raise KeyError(f"profile_pins entry '{slug}' is not present in catalog/repos.json")
        description = str(entry.get("canonical_description") or "").strip()
        if not description:
            raise ValueError(
                f"profile_pins entry '{slug}' is missing canonical_description in catalog/repos.json"
            )
        url = entry_url(entry)
        if not url:
            raise ValueError(
                f"profile_pins entry '{slug}' is missing homepage in catalog/repos.json"
            )
        lines.append(f"- [{slug}]({url}) — {description}")
    return lines


def render_domains(profile: dict) -> str:
    domains = profile.get("domains") or []
    return " · ".join(prettify_slug(d) for d in domains if d)


def render_readme(profile: dict, repos: dict[str, dict]) -> str:
    name = profile.get("full_name") or profile.get("name") or "alawein"
    bio = str(profile.get("bio_short") or "").strip()
    quote = str(profile.get("tagline_quote") or "").strip().strip('"')

    lines: list[str] = [
        "<!-- Generated by scripts/sync-readme.py. Do not edit directly. -->",
        "",
        f"# {name}",
        "",
    ]

    if bio:
        lines += [bio, ""]

    if quote:
        lines += [f"> {quote}", ""]

    link_row = render_link_row(profile)
    if link_row:
        lines += [link_row, ""]

    pin_lines = render_pins(profile, repos)
    if pin_lines:
        lines += ["## Current focus", "", *pin_lines, ""]

    domain_row = render_domains(profile)
    if domain_row:
        lines += ["## Working on", "", domain_row, ""]

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    check_only = "--check" in sys.argv
    catalogs = load_catalogs()
    profile = profile_config()
    rendered = render_readme(profile, repo_index_by_slug(repo_entries(catalogs)))
    current = README.read_text(encoding="utf-8") if README.exists() else ""

    if rendered != current:
        if check_only:
            print("README.md is out of sync. Run: python scripts/sync-readme.py")
            return 1
        README.write_text(rendered, encoding="utf-8", newline="\n")
        print("README.md updated.")
        return 0

    if check_only:
        print("README.md is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
