#!/usr/bin/env python3
"""Generate the control-plane README from canonical profile and project data."""

from __future__ import annotations

import sys
from pathlib import Path

from catalog_lib import load_catalogs, profile_config, repo_entries, repo_index_by_slug

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"


def entry_url(entry: dict) -> str:
    url = (entry.get("homepage") or entry.get("url") or "").strip()
    if url:
        return url
    if entry.get("repo"):
        return f"https://github.com/{entry['repo']}"
    return ""


def render_links(profile: dict) -> list[str]:
    urls = profile.get("urls") or {}
    ordered = [
        ("website", "Website"),
        ("morphism", "Morphism"),
        ("linkedin", "LinkedIn"),
        ("github", "GitHub"),
        ("email", "Email"),
    ]
    lines: list[str] = []
    for key, label in ordered:
        url = urls.get(key)
        if not url:
            continue
        text = url.replace("mailto:", "")
        lines.append(f"- {label}: [{text}]({url})")
    return lines


def render_pins(profile: dict, repos: dict[str, dict]) -> list[str]:
    pins = profile.get("profile_pins") or []
    lines: list[str] = []
    for slug in pins:
        entry = repos.get(slug)
        if entry is None:
            raise KeyError(f"profile_pins entry '{slug}' is not present in catalog/repos.json")
        description = str(entry.get("canonical_description") or "").strip()
        if not description:
            raise ValueError(f"profile_pins entry '{slug}' is missing canonical_description in catalog/repos.json")
        url = entry_url(entry)
        if not url:
            raise ValueError(f"profile_pins entry '{slug}' is missing homepage in catalog/repos.json")
        lines.append(f"- [{slug}]({url}) - {description}")
    return lines


def render_readme(profile: dict, repos: dict[str, dict]) -> str:
    lines = [
        "<!-- Generated by scripts/sync-readme.py. Do not edit directly. -->",
        "",
        "# alawein",
        "",
        "Control plane for the Alawein workspace. Governs style, documentation",
        "standards, and agent-facing contracts across sibling repos.",
        "",
        "This repo contains no product code. Each sibling repo is an independent",
        "git repository; this control plane defines the rules they operate under",
        "but does not own their code.",
        "",
        *render_links(profile),
        "",
        "## Structure",
        "",
        "```text",
        "docs/",
        "  style/",
        "    VOICE.md",
        "  governance/",
        "  README.md",
        "prompt-kits/",
        "  AGENT.md",
        "  PORTFOLIO.md",
        "scripts/",
        "  sync-readme.py",
        "  validate.py",
        "  validate-doc-contract.sh",
        "  validate-doctrine.py",
        "```",
        "",
        "## Portfolio signal",
        "",
        "Pinned below on GitHub carries the portfolio signal. The current focus set is:",
        "",
        *render_pins(profile, repos),
        "",
        "## Style enforcement",
        "",
        "Blocking surfaces (CI must pass before merge):",
        "- `README.md` and `docs/README.md`",
        "- `CLAUDE.md`, `AGENTS.md`, and `.claude/CLAUDE.md`",
        "- `prompt-kits/`",
        "",
        "Advisory surfaces:",
        "- Code comments",
        "- Mathematical notation",
        "- Commit messages",
        "",
        "## Governed repos (canary order)",
        "",
        "1. `alawein`",
        "2. `meshal-web`",
        "3. `workspace-tools`",
        "4. `alembiq`",
        "5. remaining governed repos",
        "",
        "## Operating rules",
        "",
        "- Never introduce YAML frontmatter into `README.md` or `docs/README.md`.",
        "- Never add AI attribution to commits, code, or documentation.",
        "- Raw corpus inputs stay out of version control. Commit only distilled",
        "  artifacts and deliberate rewrites.",
        "- Prefer fixing validators and generators over patching their outputs",
        "  manually.",
        "- Do not revert unrelated user changes in sibling repos.",
        "",
        "## License",
        "",
        "MIT. Copyright 2026 Meshal Alawein / Cache Me Outside LLC.",
        "",
    ]
    return "\n".join(lines).strip() + "\n"


def main() -> int:
    check_only = "--check" in sys.argv
    catalogs = load_catalogs()
    profile = profile_config()
    rendered = render_readme(profile, repo_index_by_slug(repo_entries(catalogs)))
    current = README.read_text(encoding="utf-8") if README.exists() else ""

    if rendered != current:
        if check_only:
            print("README.md is out of sync. Run: python scripts/sync-readme.py")
            return 1
        README.write_text(rendered, encoding="utf-8", newline="\n")
        print("README.md updated.")
        return 0

    if check_only:
        print("README.md is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
