#!/usr/bin/env python3
"""Generate the profile README from canonical project and profile data."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PROJECTS_JSON = ROOT / "projects.json"
README = ROOT / "README.md"
PROFILE_YAML = ROOT / "profile-from-guides.yaml"


def load_frontmatter_yaml(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if lines and lines[0].lstrip("\ufeff") == "---":
        for index in range(1, len(lines)):
            if lines[index] == "---":
                payload = "\n".join(lines[index + 1 :]).strip()
                return yaml.safe_load(payload) or {}
    return yaml.safe_load(text) or {}


def repo_slug(repo: str) -> str:
    return repo.rsplit("/", maxsplit=1)[-1]


def entry_url(entry: dict) -> str:
    url = (entry.get("url") or "").strip()
    if url:
        return url
    if entry.get("repo"):
        return f"https://github.com/{entry['repo']}"
    return ""


def all_projects(data: dict) -> dict[str, dict]:
    index: dict[str, dict] = {}
    for section in ("featured", "notion_sync", "research"):
        for entry in data.get(section, []):
            slug = entry.get("slug")
            if slug:
                index[slug] = entry
            repo = entry.get("repo")
            if repo:
                index[repo_slug(repo)] = entry
    return index


def render_links(profile: dict) -> list[str]:
    urls = profile.get("urls") or {}
    ordered = [
        ("website", "Website"),
        ("morphism", "Morphism"),
        ("linkedin", "LinkedIn"),
        ("github", "GitHub"),
        ("email", "Email"),
    ]
    lines: list[str] = []
    for key, label in ordered:
        url = urls.get(key)
        if not url:
            continue
        text = url.replace("mailto:", "")
        lines.append(f"- {label}: [{text}]({url})")
    return lines


def render_pins(profile: dict, projects: dict[str, dict]) -> list[str]:
    pins = profile.get("profile_pins") or []
    lines: list[str] = []
    for slug in pins:
        entry = projects.get(slug)
        if not entry:
            raise KeyError(f"profile_pins entry '{slug}' is not present in projects.json")
        url = entry_url(entry)
        description = entry.get("description", "").strip()
        lines.append(f"- [{slug}]({url}) - {description}")
    return lines


def render_readme(profile: dict, projects_data: dict) -> str:
    projects = all_projects(projects_data)
    lines = [
        "<!-- Generated by scripts/sync-readme.py. Do not edit directly. -->",
        "",
        f"# {profile.get('full_name') or profile.get('name') or 'Meshal Alawein'}",
        "",
        (profile.get("bio_short") or "").strip(),
        "",
        *render_links(profile),
        "",
        "Pinned below on GitHub carries the portfolio signal. The current focus set is:",
        "",
        *render_pins(profile, projects),
        "",
    ]
    return "\n".join(lines).strip() + "\n"


def main() -> int:
    check_only = "--check" in sys.argv
    projects_data = json.loads(PROJECTS_JSON.read_text(encoding="utf-8"))
    profile = load_frontmatter_yaml(PROFILE_YAML)
    rendered = render_readme(profile, projects_data)
    current = README.read_text(encoding="utf-8") if README.exists() else ""

    if rendered != current:
        if check_only:
            print("README.md is out of sync. Run: python scripts/sync-readme.py")
            return 1
        README.write_text(rendered, encoding="utf-8", newline="\n")
        print("README.md updated.")
        return 0

    if check_only:
        print("README.md is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
