#!/usr/bin/env python3
"""Style validator for governed Alawein surfaces."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

DEFAULT_ROOT = Path(__file__).resolve().parent.parent

SKIP_DIRS = {
    ".git",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "dist",
    "build",
    ".next",
    ".turbo",
    "coverage",
    "playwright-report",
    "test-results",
    "state",
}
SKIP_PATH_PREFIXES = ("docs/archive/",)
SKIP_GENERATED_MARKERS = (
    "# AUTO-GENERATED",
    "# This file is generated",
    "<!-- AUTO-GENERATED -->",
    "<!-- generated by",
    "<!-- Generated by scripts/sync-readme.py.",
)

FORBIDDEN_REGISTER = [
    r"\bpassionate about\b",
    r"\bleveraging\b",
    r"\binnovative\b",
    r"\bcutting-edge\b",
    r"\bexcited to\b",
    r"\bit'?s worth noting\b",
    r"\binterestingly\b",
    r"\bdelve into\b",
    r"\bdeep dive\b",
    r"\butilize\b",
    r"\bin today'?s world\b",
    r"\bmoving forward\b",
    r"\bsynergy\b",
    r"\bholistic\b",
    r"\bgame-changing\b",
    r"\bgroundbreaking\b",
    r"\bseamlessly\b",
    r"\brobust solution\b",
    r"\bempower\b",
    r"\btransformative\b",
    r"\bI am pleased to\b",
    r"\bI hope this helps\b",
    r"\bfeel free to\b",
    r"\bas mentioned above\b",
]
AI_ATTRIBUTION_PATTERNS = [
    r"Generated with Claude",
    r"Co-Authored-By: Claude",
    r"Generated by (Claude|ChatGPT|OpenAI|Anthropic)",
    r"\bAI-generated\s+(?:with|by|via)\b",
]
STALE_IDENTITY_PATTERNS = [
    r"\balaweimm90\b",
    r"\bmalawein\.com\b",
]
FRONTMATTER_RE = re.compile(r"\A---\s*\r?\n.*?\r?\n---\s*(?:\r?\n|$)", re.DOTALL)


@dataclass
class Violation:
    path: Path
    line: int
    rule: str
    detail: str
    tier: Literal["blocking", "advisory"]

    def __str__(self) -> str:
        label = "BLOCK" if self.tier == "blocking" else "WARN "
        return f"[{label}] {self.path}:{self.line} - {self.rule}: {self.detail}"


@dataclass
class Report:
    violations: list[Violation] = field(default_factory=list)

    def add(self, violation: Violation) -> None:
        self.violations.append(violation)

    @property
    def blocking(self) -> list[Violation]:
        return [v for v in self.violations if v.tier == "blocking"]

    @property
    def advisory(self) -> list[Violation]:
        return [v for v in self.violations if v.tier == "advisory"]

    def print_summary(self) -> None:
        if not self.violations:
            print("OK - no violations found.")
            return
        for violation in self.violations:
            print(violation)
        print()
        print(f"Summary: {len(self.blocking)} blocking, {len(self.advisory)} advisory")


def should_skip(path: Path, root: Path) -> bool:
    rel = path.relative_to(root).as_posix()
    if any(part in SKIP_DIRS for part in path.parts):
        return True
    return rel.startswith(SKIP_PATH_PREFIXES)


def is_generated(content: str) -> bool:
    head = content[:512].lower()
    return any(marker.lower() in head for marker in SKIP_GENERATED_MARKERS)


def is_blocking_surface(path: Path) -> bool:
    rel = path.as_posix()
    if path.name == "README.md":
        return True
    if path.name in {"CLAUDE.md", "AGENTS.md"}:
        return True
    return "/prompt-kits/" in f"/{rel}/"


def collect_paths(root: Path) -> list[Path]:
    candidates: list[Path] = []
    for pattern in ("README.md", "docs/README.md", "CLAUDE.md", "AGENTS.md", "prompt-kits/*.md"):
        candidates.extend(root.glob(pattern))
    for path in root.rglob("*.md"):
        if should_skip(path, root):
            continue
        rel = path.relative_to(root).as_posix()
        if rel in {"README.md", "docs/README.md", "CLAUDE.md", "AGENTS.md"}:
            continue
        if rel.startswith("prompt-kits/"):
            candidates.append(path)
    unique: dict[str, Path] = {}
    for path in candidates:
        if should_skip(path, root):
            continue
        unique[path.resolve().as_posix()] = path.resolve()
    return sorted(unique.values())


def add_match_violations(
    report: Report,
    path: Path,
    content: str,
    patterns: list[str],
    rule: str,
    tier: Literal["blocking", "advisory"],
) -> None:
    for line_no, line in enumerate(content.splitlines(), start=1):
        for pattern in patterns:
            if re.search(pattern, line, re.IGNORECASE):
                report.add(
                    Violation(
                        path=path,
                        line=line_no,
                        rule=rule,
                        detail=line.strip()[:160],
                        tier=tier,
                    )
                )


def check_frontmatter(path: Path, content: str, report: Report) -> None:
    rel = path.as_posix()
    if rel.endswith("README.md") and FRONTMATTER_RE.match(content):
        report.add(
            Violation(
                path=path,
                line=1,
                rule="frontmatter",
                detail="YAML frontmatter found in a GitHub-facing README surface",
                tier="blocking",
            )
        )


def run_checks(paths: list[Path], checks: set[str], report: Report) -> None:
    for path in paths:
        try:
            content = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, PermissionError):
            continue
        if is_generated(content):
            continue

        if "frontmatter" in checks:
            check_frontmatter(path, content, report)

        if "voice" in checks:
            add_match_violations(
                report,
                path,
                content,
                FORBIDDEN_REGISTER,
                "forbidden-register",
                "blocking" if is_blocking_surface(path) else "advisory",
            )

        if "attribution" in checks:
            add_match_violations(
                report,
                path,
                content,
                AI_ATTRIBUTION_PATTERNS,
                "ai-attribution",
                "blocking" if is_blocking_surface(path) else "advisory",
            )

        if "identity" in checks:
            add_match_violations(
                report,
                path,
                content,
                STALE_IDENTITY_PATTERNS,
                "stale-identity",
                "blocking" if is_blocking_surface(path) else "advisory",
            )


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate governed style surfaces")
    parser.add_argument(
        "--check",
        choices=["frontmatter", "voice", "attribution", "identity", "all"],
        default="all",
    )
    parser.add_argument("--paths", nargs="*", help="Specific file paths to check")
    parser.add_argument("--root", default=str(DEFAULT_ROOT), help="Repository root to scan")
    parser.add_argument("--ci", action="store_true", help="Exit non-zero on blocking violations")
    args = parser.parse_args()

    checks = {"frontmatter", "voice", "attribution", "identity"} if args.check == "all" else {args.check}
    root = Path(args.root).resolve()

    if args.paths:
        paths = [Path(p).resolve() for p in args.paths]
    else:
        paths = collect_paths(root)

    report = Report()
    run_checks(paths, checks, report)
    report.print_summary()

    if args.ci and report.blocking:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
