output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_name" {
  description = "EKS cluster name"
  value       = module.eks.cluster_name
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "cluster_iam_role_arn" {
  description = "IAM role ARN of the EKS cluster"
  value       = module.eks.cluster_iam_role_arn
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = module.eks.cluster_certificate_authority_data
  sensitive   = true
}

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster's OIDC Issuer"
  value       = module.eks.cluster_oidc_issuer_url
}

output "node_security_group_id" {
  description = "Security group ID attached to the EKS nodes"
  value       = module.eks.node_security_group_id
}

output "vpc_id" {
  description = "The ID of the VPC"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "The CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnet_ids" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnet_ids" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

output "nat_gateway_ids" {
  description = "List of NAT Gateway IDs"
  value       = module.vpc.natgw_ids
}

output "rds_endpoint" {
  description = "Connection endpoint for RDS instance"
  value       = module.rds.db_instance_endpoint
}

output "rds_database_name" {
  description = "Name of the RDS database"
  value       = module.rds.db_instance_name
}

output "redis_endpoint" {
  description = "Redis cluster endpoint"
  value       = var.environment == "production" ? module.elasticache.replication_group_primary_endpoint_address : module.elasticache.cluster_address
}

output "s3_bucket_id" {
  description = "The name of the S3 bucket"
  value       = module.s3_bucket.s3_bucket_id
}

output "s3_bucket_arn" {
  description = "The ARN of the S3 bucket"
  value       = module.s3_bucket.s3_bucket_arn
}

output "irsa_role_arn" {
  description = "ARN of IAM role for service account"
  value       = module.mezan_atlas_irsa.iam_role_arn
}

output "cloudwatch_log_groups" {
  description = "CloudWatch log groups created"
  value = {
    redis = aws_cloudwatch_log_group.redis.name
    rds   = module.rds.db_instance_cloudwatch_log_groups
  }
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = templatefile("${path.module}/templates/kubeconfig.tpl", {
    cluster_name = module.eks.cluster_name
    endpoint     = module.eks.cluster_endpoint
    ca_data      = module.eks.cluster_certificate_authority_data
    region       = var.aws_region
  })
  sensitive = true
}

output "helm_values" {
  description = "Generated Helm values for MEZAN ATLAS deployment"
  value = templatefile("${path.module}/templates/helm-values.tpl", {
    environment      = var.environment
    registry         = "${data.aws_caller_identity.current.account_id}.dkr.ecr.${var.aws_region}.amazonaws.com"
    redis_endpoint   = var.environment == "production" ? module.elasticache.replication_group_primary_endpoint_address : module.elasticache.cluster_address
    rds_endpoint     = split(":", module.rds.db_instance_endpoint)[0]
    s3_bucket        = module.s3_bucket.s3_bucket_id
    irsa_role_arn    = module.mezan_atlas_irsa.iam_role_arn
  })
}

output "deployment_commands" {
  description = "Commands to deploy MEZAN ATLAS"
  value = <<-EOT
    # Configure kubectl
    aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks.cluster_name}

    # Deploy with Helm
    helm upgrade --install mezan-atlas \
      ./MEZAN/ATLAS/atlas-core/helm \
      --namespace mezan-atlas-${var.environment} \
      --create-namespace \
      --values ./MEZAN/ATLAS/atlas-core/helm/values-${var.environment}.yaml \
      --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="${module.mezan_atlas_irsa.iam_role_arn}" \
      --set redis.host="${var.environment == "production" ? module.elasticache.replication_group_primary_endpoint_address : module.elasticache.cluster_address}" \
      --set postgresql.host="${split(":", module.rds.db_instance_endpoint)[0]}" \
      --set backup.s3.bucket="${module.s3_bucket.s3_bucket_id}" \
      --wait --timeout 10m

    # Verify deployment
    kubectl get pods -n mezan-atlas-${var.environment}
    kubectl get svc -n mezan-atlas-${var.environment}
  EOT
}